pabi2/pb2_addons

hr_expense_advance_clearing/data/invoice_workflow.xml, pabi_account/models/account.py, pabi_hr_expense/views/account_invoice_view.xml
Module require updates,
* hr_expense_advance_clearing -> fix cancel workflow
* pabi_hr_expense -> fix cancel button
* pabi_apps_config -> default update
:100755 100755 255b80ab 296ff404 M	hr_expense_advance_clearing/data/invoice_workflow.xml
:100755 100755 418caa6a 30b605ad M	pabi_account/models/account.py
:100755 100755 8603094e 07953185 M	pabi_hr_expense/views/account_invoice_view.xml
=> [FIX] fix for issue 3036, use cancel reason for case cancel AV Clearing

account_budget_activity/models/budget_commit.py, pabi_budget_drilldown_report/models/analytic.py, pabi_budget_drilldown_report/views/analytic_view.xml
This commit require update of
1) account_budget_activity -> To create compute field net_committed_amount
2) pabi_budget_drilldown_report -> to add new column into analytic view
Note: since account_budget_activity is updated, please also update 
- pabi_budget_monitor
- pabi_budget_plan_monitor
- pabi_etl
and also, final with
- pabi_apps_config
Note2: Please deploy and test on test server first.
:100755 100755 c79a81eb 4b9ddd36 M	account_budget_activity/models/budget_commit.py
:100644 100644 b739daac 067c2444 M	pabi_budget_drilldown_report/models/analytic.py
:100644 100644 2039e056 9cd21d9b M	pabi_budget_drilldown_report/views/analytic_view.xml
=> [ENH] add new column net_committed_amount in analytic_view

account_budget_activity/models/budget_commit.py
FIX ERROR: 
cannot marshal None unless allow_none is enabled
TypeError: cannot marshal None unless allow_none is enabled
=> fix recreate_all_budget_commitment call api error

pabi_account_report/reports/xlsx_report_gl_project.xml, pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml, pabi_budget_monitor/report/budget_monitor_report_wizard_view.xml
ปรับเงื่อนไขการแสดง Project List ใน Filter ให้แสดงสถานะที่เป็น Active = False ด้วย
ในรายงานต่อไปนี้
-เมนู Accounting >> Reports >> General Ledger >> GL Project
-เมนู Budgeting >> Budget Monitor >> Budget Monitoring
-เมนู Budgeting >> Budget Monitor >> Budget Overview Report
-เมนู Budgeting >> Budget Report >> My Budget Report
=> #3177 ปรับแก้เงื่อนในการแสดงรายงาน โดยให้แสดง Project ที่ Inactive ใน

pabi_async_process/pabi_action_asset_compute/pabi_action_asset_compute.py, pabi_async_process/pabi_action_asset_compute/pabi_depre_batch.py
1. เมนู Accounting -> Periodic Processing -> Recurring Entries -> Compute Assets
หลักการ
- เมื่อกดปุ่ม Execute ให้ตรวจสอบ model = pabi.asset.depre.batch ต้องไม่มี state = Draft อยู่เลย
หากยังมี state = Draft ให้แสดง Error เป็นข้อความว่า "Please delete the Draft state in the Asset Depre. Batch menu!!"(แก้แสดง error เก่า)
2. เมนู Accounting -> Periodic Processing -> Asset Depre. Batch
หลักการ
- เมื่อกดปุ่ม Post Entires กรณีมี state=Draft มากกว่า 1 อัน ให้แสดง Error ข้อความว่า "Please check the Asset Depre. Batch menu, don't list the Draft state more than one!!"
=> #3162_async_process

pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml
-เมนู Budgeting > Budget Report > My Budget Report 
ปรับเงื่อนไขการแสดง Project List ใน Filter ให้แสดงสถานะที่เป็น Active = False
=> #3177: ปรับแก้เงื่อนในการแสดงรายงาน โดยให้แสดง Project ที่ Inactive ใน List

pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml
1.เมนู ฺBudgeting >> Budget Monitor >> Budget Overview Report
- ปรับเงื่อนไขการแสดง Section List ใน Filter ให้แสดงสถานะที่เป็น Active = False ด้วย
- ใน List(Report Type: All) เมื่อกรอก Section ที่ Active = False แสดง Section ที่ช่อง Print Only 
2. เมนู ฺBudgeting >> Budget Report >> My Budget Report
- ปรับเงื่อนไขการแสดง Section List ใน Filter ให้แสดงสถานะที่เป็น Active = False ด้วย
=> #3198: รายงาน Budget Overview Report และ  My Budget Report 

pabi_purchase_invoice_plan/models/stock.py, pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
To update -> pabi_purchase_work_acceptance
This should create new field **purchase_work_acceptance.price_unit_untaxed** and compute its values, please check.
=> [FIX] #2939 asset use wrong value case tax included

pabi_async_process/pabi_action_asset_compute/pabi_depre_batch.py
This fix just to make sure the move_id is cleared properly. (The old code also has no problem)
Just pull and restart.
=> [FIX] set null to account_asset_line.move_id when its test JE is deleted

pabi_account_report/__openerp__.py
เนื่องจาก model xlsx.report.preprint.receipt ยังไม่พร้อมใช้งาน
=> comment xlsx_report_preprint_receipt.xml ออกก่อน

l10n_th_amount_text/all_docs.py
Module : l10n_th_amount_text
FI : PO จำนวนเงินรวมเป็นตัวอักษรแสดงไม่ถูกต้อง
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3638
=> Branch : #3638_Round_Total

l10n_th_doctype_bank_receipt/models/account_bank_receipt.py
Deployment:
- Restart only
Problem:
- ปัญหาที่มีคือ ตอนนี้ระบบใช้ Today ในการรันเลขที่เอกสาร
Solution:
- Use posting date for document sequence (instead of today)
=> [FIX] l10n_th_doctype_bank_recipt

account_budget_activity/models/budget_commit.py
คิดว่าปัญหาน่าจะเกิดจาก การ release_budget_commitment ครั้งแรกเท่านั้น จึงเป็นเหตุผลว่าการทำ recreate budget commitment แล้วถึงจะโอเค
เนื่องจากการ release_budget_commitment ครั้งแรกจะเป็นการ Copy() และกลับรายการจาก commitment ครั้งก่อนหน้าโดยการใช้วันที่เดียวกัน จากโค้ดส่วนนี้ budget_commit.py -> release_committed_budget()
จึงทำให้มันกลับไปใช้วันที่และปีเดิม 2019 แทนที่ปีใหม่ที่เราต้องการ 2020
**Solution:**
สำหรับการ release_committed_budget -> เปลี่ยนวันที่ date เป็นปัจจุบัน
=> [FIX] 3878 - รายการผูกพัน PO ที่ยกยอดผูกพันพบว่าปี 2020 มียอดเบิ้ล

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
module : pabi_purchase_work_acceptance
PO : Can't evaluate this acceptance. This WA's total amount is over PO's
total amount.
Issues : https://mobileapp.nstda.or.th/redmine/issues/3786
=> #3786_PO_Invoice_Plan

account_budget_activity/models/account_budget.py, pabi_budget_plan/models/budget_plan/budget_plan_common.py
Deployment
- Restart only
BG: Budget BreakDown ValidateError Plan/UNIT/2000024
ทั้งทีมีใน Budget Plan แล้วในปี 2020
=> [FIX] #3863 BG: Budget BreakDown ValidateError

l10n_th_account/models/account_invoice.py, l10n_th_account/models/account_voucher.py, l10n_th_account/models/account_wht_cert.py
module:l10n_th_account
FI: Menu Supplier Invoice and Supplier Payment ให้เช็ควันที่ Due Date ต้องระบุมากกว่าหรือเท่ากับ Posting Date และ Default Withholding Tax
Issues:https://mobileapp.nstda.or.th/redmine/issues/4106
=> #4106_date_check

pabi_asset_management/models/stock.py
จากที่ได้ตรวจสอบปัญหาพบว่าเกิดจาก
- สถานะของ Asset เป็น active = False ทำให้ระบบไม่สามารถนับจำนวน Asset ที่เกิด/เคยเกิดขึ้นได้
จึงเกิดกรณีที่ เมื่อทำการยกเลิก Asset ปุ่ม Smart Button หายไป
ทำการแก้ไขโดย
- ให้ระบบทำการนับ Asset ที่เกิดขึ้น
- เมื่อกดปุ่ม smart button "Assets" จะแสดง Assets ที่เกิดขึ้น (Active = False and True)
=> #4143 - Smart Button แสดงข้อมูล Assets หลังจากถูก Remove หายไป

pabi_mis_account_financial_report/__init__.py, pabi_mis_account_financial_report/__openerp__.py, pabi_mis_account_financial_report/data/mis.report.kpi.csv, pabi_mis_account_financial_report/data/mis_report_bs.xml, pabi_mis_account_financial_report/models/__init__.py, pabi_mis_account_financial_report/models/mis_builders.py, pabi_mis_account_financial_report/reports/__init__.py, pabi_mis_account_financial_report/reports/mis_builder_xlsx.py, pabi_mis_account_financial_report/views/mis_builder.xml
เปลี่ยนวิธีการรันรายงานเป็นแบบ MIS Builder
สามารถรันออกมาได้ทั้ง 3 แบบ คือ view, pdf และ excel
วิธีการใช้งาน
1. install module mis_builder
2. install module pabi_mis_account_financial_report
3. go to Accounting -> Reporting -> MIS Reports
4. create mis และเลือก Report ที่ต้องการ (ตัวอย่างจะทำ งบแสดงฐานะทางการเงิน)
5. ใน line เลือก Period type -> Fiscal Period และ set ช่วงเวลาที่ต้องการดู
6. save และสามารถดู Preview, PDF, Excel ได้ที่ปุ่มด้านขวา
การใช้ CSS Style Sheet
สำหรับการ Export เป็น Excel จะมีข้อจำกัดคือ
- การใช้ `text-indent` สามารถทำได้สูงสุด 2 ชั้นคือ
`text-indent: 50px` = indent 1 ชั้น
`text-indent: 100px` = indent 2 ชั้น
=> #3992 [ADD] pabi_mis_account_financial_report

account_budget_activity/models/analytic.py
แก้ไขการลงผิด budget เมื่อเลือก budget เป็น invest asset และทำรายการมากกว่า 1 ชิ้น
สาเหตุเกิดจากการขียน code ไม่มีการเรียงลำดับ id ที่หามาได้ ทำให้ระบบดึงมาคนละตัวกัน
แก้ไขโดยการเพิ่ม `sorted()` ให้ระบบเรียงลำดับให้ถูกต้อง
=> #4152 [FIX] create po budget wrong budget (invest asset budget)

pabi_validate_pricediff/__init__.py, pabi_validate_pricediff/__openerp__.py, pabi_validate_pricediff/models/__init__.py, pabi_validate_pricediff/models/invoice.py
จากกรณีที่เกิด price diff โดยไม่ทราบสาเหตุ จึงทำการเพิ่ม module ชั่วคราวที่เมื่อเกิด price diff ระบบจะขึ้นแจ้งเตือน และให้ user ติดต่อ เพื่อหาสาเหตุที่แท้จริงทันทีครับ
ซึ่งปกติแล้วการเกิด price diff ของ invoice จะเกิดเมื่อ
- invoice line แต่ละบรรทัดไม่สัมพันธ์กับ purchase order line (อาจเกิดจากการลบบรรทัดใน invoice line หรือ purchase line แล้วสร้างใหม่ ซึ่งใบที่สร้างใหม่จะไม่ได้เชื่อมกัน ทำให้เกิด price diff)
issue : https://mobileapp.nstda.or.th/redmine/issues/3948
**Deployment** : install module 'pabi_validate_pricediff'
=> #3948 [ADD] pabi_validate_pricediff for find case

pabi_purchase_contract/views/purchase_contract_view.xml
Issue : https://mobileapp.nstda.or.th/redmine/issues/4193
ซ่อนปุ่ม Delete ที่ tree/form view in PO Contract
Update This Only : Module - pabi_purchase_contract
=> [FIX] 4193: hide_action_delete in PO Contract

pabi_account_financial_report_webkit/report/common_partner_reports.py
https://mobileapp.nstda.or.th/redmine/issues/4207
แก้ไขการ quary
ยกตัวอย่าง: Entry IA20001668 มีการ reconcile ณ วันที่ 8 เดือน 11
เมื่อเรียกรายงาน Open Invoices ในเดือน 10 (01/2020) จะได้ผลดังรูป
เมื่อเรียกรายงาน Open Invoices ในเดือน 11 (02/2020) จะได้ผลดังรูป
=> [FIX] Issues - 4207

pabi_asset_management/models/asset_adjust.py
แก้ไขการที่ asset_to_expense ไม่สามารถ adjust ได้
สาเหตุเกิดจาก move line ของ asset เก่า ไม่มีค่า account analytic
ทำให้ระบบไม่ได้คืน budget กลับ ส่งผลให้ budget นั้นๆมียอดเป็น 2 เท่า
แก้ไขโดยการเพิ่ม account analytic เพื่อให้ระบบสามารถคืน budget ได้ถูกต้อง
=> #4265 [FIX] asset to expense

pabi_procurement/views/purchase_view.xml
Module : pabi_procurement
PO : ไม่สามารถ Group by Operating Unit ข้อมูล Purchases ในหน้า Product >
Purchase ได้
Issues : https://mobileapp.nstda.or.th/redmine/issues/3328
=> #3328_Group_By_operating_Unit_Fix

pabi_my_project/models/res_project.py
แก้ไขเมื่อระบบอื่นส่งค่า budget plan expense แต่ไม่ส่งปีที่เคยมีในระบบมา
ให้ระบบตรวจสอบ budget_plan_ids ถ้ามี internal จะให้ระบบ return ค่ากลับไม่ต้อง released amount
=> #4261 [FIX] project_interface_expense error

account_budget_activity/models/analytic.py
เพิ่ม index ให้กับบาง fields จะทำให้ระบบทำงานได้เร็วขึ้น
create analytic line เร็วขึ้น
จากเดิม 0.8 วินาที/ใบ เป็น 0.3 วินาที/ใบ
ส่งผลกับทุกปุ่มที่มีการสร้าง analytic line เช่น
- Confirm PO
- IN Transfer
Deployment : restart and update module 'account_budget_activity'
cherry-pick from https://github.com/pabi2/pb2_addons/pull/1817
=> #4314 [FIX] Performance Index analytic

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py, pabi_purchase_work_acceptance/wizard/create_purchase_work_acceptance.py
Performance WA
---------------------------------------
- แก้ไขการสร้าง WA
จากเดิม สร้าง WA แล้ว write wa_line ทับไปอีกทีหนึ่ง
แก้เป็น สร้าง wa_line ให้เสร็จก่อน (เป็น dict) แล้วสร้าง WA พร้อม line ทีเดียว
- แก้ไขการเรียกใช้งาน function button_reset_taxes
จากเดิมระบบจะเรียก function นี้ทุกครั้ง ทีละครั้งใช้เวลาประมาณ 0.8 วินาที
แก้เป็น วน loops เก็บค่า invoices ทั้งหมดมาก่อนแล้วค่อยเรียก function นี้ทีเดียว
วิธีทดสอบ
1. สร้าง PO Lines 10 บรรทัด เลือก use invoice plan
2. แบ่งเป็น 2 งวด -> Create Invoices
3. Create Work Acceptance เลือกจ่ายงวดที่ 1
ผลการทดสอบ
จากเดิมใช้เวลา 60 วินาที เหลือ 8 วินาที
Deployment : Restart only
=> #4314 [FIX] performance turning WA case invoice plan

pabi_my_project/models/res_project.py, pabi_my_project/views/res_project_view.xml
ย้าย Tab Budget Monitor ในหน้า myProject ไปอยู่ที่ Smart Button เพื่อให้ระบบแสดงผลลัพธ์ได้เร็วขึ้น
ผลการทดสอบคือ ไปที่เมนู myProject -> คลิก Project แล้วระบบแสดงผลลัพธ์ทันที
และหากต้องการดู Budget Monitor ให้กดที่ Smart Button ด้านบนขวาแทน
ระบบจะได้ไม่ต้องแสดง Budget Monitor ทุก Project เพราะบางทีเราอาจจะดูข้อมูลอื่นๆ ซึ่งจะเสียเวลาในการโหลด (แต่เมื่อคลิกเข้าใน Budget Monitor ระบบจะยังใช้เวลาโหลดนานเหมือนเดิม)
Deployment : restart and update module 'pabi_my_project'
=> #4418 [FIX] move budget monitor in myProject to SmartButton

pabi_mis_account_financial_report/reports/mis_builder_xlsx.py
Issue: https://mobileapp.nstda.or.th/redmine/issues/4416
Deployment: Restart
กรณีกำหนดค่า default_css_style = font-weight: bold; text-align: right; สามารถแสดงผลใน XLSX ให้เป็น "ตัวหนา และ ชิดทางด้านขวา" ได้
PDF: https://github.com/pabi2/pb2_base_technical/pull/44
=> #4416 - mis_builder

pabi_budget_monitor/models/res_spa_structure.py, pabi_my_project/models/res_project.py, pabi_my_project/views/res_project_view.xml
แก้ไขให้เป็น Budget Monitor กลับมาอยู่ที่ Tab เหมือนเดิมและปรับ performance ให้เร็วขึ้น
Deployment : Restart and update module pabi_my_project and pabi_budget_monitor
reference : https://github.com/pabi2/pb2_addons/pull/1826
=> #4418 [FIX] change back to main myProject

pabi_validate_pricediff/models/invoice.py
แก้ไขการคำนวณ price diff ที่ผิดพลาด
จากปกติระบบจะเทียบ price unit จาห stock.move
เปลี่ยนเป็นให้ระบบ check จาก purchase_line แทน ซึ่งน่าจะถูกต้องมากกว่า
=> #4443 [FIX] price diff on stock.move

account_budget_activity/models/account_move_line.py, account_budget_activity/models/analytic.py, pabi_asset_management/models/asset.py, pabi_asset_management/models/asset_removal.py, pabi_asset_management/wizard/account_asset_remove.py
สาเหตุอาจเกิดจากการที่มีการ check ก่อนสร้าง analytic_line
ซึ่งจะเกิดกรณีที่สร้าง PO lines หลายบรรทัด แล้วระบบสร้าง analytic line ไม่ทัน
ทำให้บางค่าระบบไม่เจอ line แล้วจึงข้ามบางขั้นตอนไป
- แก้ไขการ check เงื่อนไขหลังสร้าง analytic_line ซึ่งจะมั่นใจได้ว่าเกิด analytic_line แน่นอน
ฉะนั้นระบบจะทำงานถูกต้อง เมื่อมีการสร้างหลายๆ PO lines
- แก้ไขการบันทึก OU ของ asset โดยใช้ owner_OU_id แทน OU_id เมื่อ remove asset จากทั้ง master asset และ action removal
- แก้ไขการบันทึก move line กรณีที่เกิดผลต่าง โดยดูจาก Removal Entry Policy
-- กรณีที่เป็น gain/loss แล้วมีผลต่าง ระบบจะสร้าง move_line อีกบรรทัด โดยดู account จาก min value account (dr.) และ plus value account (cr.)
-- กรณีที่เป็น residual value แล้วมีผลต่าง ระบบจะสร้าง move_line โดยดู account จาก residual value account
Deployment : Restart and …
=> #4429 [FIX] change analytic_line for check after create only

pabi_budget_monitor/models/res_spa_structure.py
แก้ไข error เมื่อสร้าง project ใหม่
สาเหตุเกิดจากระบบเป็น compute field และมีการ query ทุกครั้งที่มีการเปลี่ยนแปลง
แต่ id ที่ส่งมาเมื่อสร้าง project ใหม่ยังไม่มี ระบบจึง query หา id นั้นไม่เจอจึงเกิด error
แก้ไขโดยการ check id ก่อน ถ้าไม่มี id ให้ return ค่ากลับไป ไม่ต้อง query
=> #4466 [FIX] error when create new myproject

pabi_validate_pricediff/models/invoice.py
สาเหตุคือแก้ไข bug จาก แก้ไข code จาก issue https://mobileapp.nstda.or.th/redmine/issues/4443
ซึ่งส่งผลให้กรณีที่มี currency ระบบจะแปลงสกุลเงินซ้ำอีกครั้งหนึ่ง
ทำให้ค่าที่ได้ผิดพลาด
แก้ไขโดยการ check เงื่อนไข ว่ามี currency หรือไม่
ทดสอบทั้ง 2 issue แล้วสามารถทำงานได้ถูกต้อง
Deployment : restart only
=> #4474 [FIX] price diff case currency prepaid and not currency

pabi_account_move_adjustment/models/stock_account.py, pabi_account_move_adjustment/views/stock_view.xml, pabi_asset_management/models/stock_account.py
Issue: https://mobileapp.nstda.or.th/redmine/issues/4459
Deployment: restart & update this only module: pabi_account_move_adjustment
แก้ไขให้ระบบบันทึกบัญชีเข้า บัญชีค่าใช้จ่าย แทน เฉพาะกรณีถ้าเป็นการปรับปรุง inventory adjust
cr: Stock Output Account
=> #4459 - Fix account_id when create from Inventory Adjustments

pabi_account_financial_report_webkit/account.py, pabi_account_financial_report_webkit/report/common_reports.py, pabi_account_financial_report_webkit/report/general_ledger.py, pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py
Issue: https://mobileapp.nstda.or.th/redmine/issues/4208
Deployment: Restart & Update this only module " pabi_account_financial_report_webkit " & " pabi_account_financial_report_webkit_xls "
เพิ่ม Column " Balance " ในการเรียกรายงาน Excel 
Column ดังกล่าวจะคำนวณ ยอดที่ยังคงค้าง ณ วันที่ทำการเรียกรายงาน
เอกสาร Reconcile เลขที่ A270656 มียอด Debit 6,666,666.66
มีการแบ่งจ่ายทั้งหมด 9 ครั้งดังรูป
เมื่อเรียกรายงาน Period ที่ 3 (01/12/2019 - 31/12/2019)
ยอด Balance ของ Reconcile เลขที่ A270656 จึงมีค่าเท่ากับ
6,666,666.66 - (111,333.32 * 8) = 5,776,000.10
ระบบจะแสดง 5,776,000.10 ทั้ง 3 บรรทัด เนื่องจาก มี Part.ID เดียวกัน
กรณีมีการสร้าง Customer Invoice แต่ยังไม่ได้ทำการ Reconcile ระบบจะแสดงยอดค้างชำระ
=> [8.0][ADD] Column - Amount Unpaid, Debit - Credit, Date Reconciled

pabi_account_financial_report_webkit/report/common_reports.py
https://mobileapp.nstda.or.th/redmine/issues/4564
deployment: Restart
Error เกิดจากระบบดึงข้อมูลผิดพลาด
รายงานที่ได้รับการแก้ไข อิงตาม https://mobileapp.nstda.or.th/redmine/issues/4301 กรณี Account ไม่ใช่ AP&AR ไม่ต้องแสดง "Amount Unpaid"
=> [FIX] - list index out of range from account is empty

pabi_asset_management/models/asset_adjust.py
https://mobileapp.nstda.or.th/redmine/issues/4544
ระบบ Error เนื่องจากกรณีระบบไม่สามารถหาข้อมูลของ move_id ได้
จึงเพิ่มเติมเงื่อนไข ให้เช็ค move_id ก่อน
=> #4544 - [FIX] asset_adjust when move_id is False

account_budget_activity/models/budget_commit.py, l10n_th_account/models/account_voucher.py
แก้ 2  ไฟล์ 
1 commit Fix sigleton แก้ไข Error เมื่อ Export Payment
commit  "Backward to origin" จาก pr https://github.com/pabi2/pb2_addons/pull/1883 แก้ไขไฟล์ผิดที่ account_budget_activity/models/budget_commit.py จึงย้อนกลับให้เป็นเหมือนเดิม
อ้างอิง 
https://mobileapp.nstda.or.th/redmine/issues/4583
=> #4583 Fix Singleton Error

l10n_th_account/models/account_voucher.py
https://github.com/pabi2/pb2_addons/pull/1885
ไม่ได้แก้ไข เมื่ออยู่ for loop ใช้ rec แต่เมื่อเรียกฟังก์ชัน ใช้ self
=> Change self -> rec

account_budget_activity/models/budget_commit.py, pabi_budget_internal_charge/models/hr_expense.py
https://mobileapp.nstda.or.th/redmine/issues/4570
ให้ระบบตรวจสอบ Control External Charge Only และ Pay Type 
หากไม่ได้ติ๊ก Control External Charge Only และ Pay Type เป็น Internal Charge
เมื่อทำการกด "Recreate budget commitment" 
Charge Type จะเป็น Internal
=> Check control_ext_charge_only and Pay Type

pabi_asset_management/models/asset.py
https://mobileapp.nstda.or.th/redmine/issues/4556
สาเหตุที่ระบบคำนวณ Day Asset ที่ Import ผิดเนื่องจากระบบไม่ได้เช็คกับ Day ก่อนหน้า จึงต้องเพิ่ม date ส่งผ่าน context เพื่อใช้คำนวณ Day 
https://github.com/pabi2/pb2_base_functional/pull/11
=> #4556 - Calculate Days - Import case

pabi_purchase_billing/models/purchase_billing.py
แก้ไขให้ระบบหา wa กรณีที่มี wa มากกว่า 1 ค่าระบบจะเลือกงวดที่เก่าสุดเสมอ (กรณีที่ user เลือกผิดงวด)
=> #4545 [FIX] find wa 1 only

l10n_th_fields/views/voucher_payment_receipt_view.xml
FI : แก้ไขการแสดงผล เมื่อเลือก Receipt Type ที่ไม่ใช่ cheque
ให้ซ่อนฟิลด์ Cheque No.
Module : l10n_th_fields
Issues : https://mobileapp.nstda.or.th/redmine/issues/4692
=> #4692_Invisible_Cheque_No

pabi_budget_monitor/models/res_org_structure.py, pabi_budget_monitor/models/res_spa_structure.py, pabi_budget_monitor/views/res_org_structure_view.xml, pabi_budget_monitor/views/res_spa_structure_view.xml, pabi_user_profile/views/res_section_view.xml
ทำการเพิ่ม smart button ที่ Project Budget Structure และ Section Budget Structure
Deployment:
1.Restart Odoo
2.Update Module: pabi_user_profile
3.Update Module: pabi_budget_monitor
Issue : https://mobileapp.nstda.or.th/redmine/issues/4676
=> [8.0][ENH]_Smart_Button

pabi_asset_management/models/asset.py
แก้ไขการคำนวณค่าเสื่อม
กรณีที่มีการ import asset จะให้ return ค่าเดิมของ asset line ที่ระบบคำนวณได้
=> #4729 [FIX] return origin asset line when import asset

pabi_asset_management/models/asset_request.py
แก้ไขให้ระบบสามารถยกเลิกได้
สาเหตุเกิดจากการเขียนชื่อ field ผิด หรือชื่อ field มีการเปลี่ยนแปลง
จาก room เป็น room_id
=> #4748 [FIX] change field name

account_budget_activity/models/budget_transition.py
แก้ไขให้ระบบแสดง CV เมื่อ KV Cancel (สำหรับ PO)
=> [FIX] CV in target budget transition

stock_picking_cancel/models/stock.py
สร้างการ trigger return budget PO เมื่อมีการกด cancel IN
=> #4906 [FIX] trigger back to PO, when cancel IN

pabi_budget_plan/models/account_budget.py
- แก้ไขให้ระบบสามารถสร้าง budget control ได้
แม้ว่า budget plan จะเป็น internal
- แก้ไขให้ระบบแสดง validate error ให้ถูกต้อง
ปกติ error นี้จะต้องขึ้นเป็น
=> [FIX] budget breakdown internal

account_budget_activity/__openerp__.py, account_budget_activity/views/purchase_view.xml, account_budget_activity/wizard/__init__.py, account_budget_activity/wizard/edit_po_line_fy.py, account_budget_activity/wizard/edit_po_line_fy.xml, pabi_purchase_billing/views/purchase_billing_view.xml, pabi_purchase_work_acceptance/models/account_invoice.py, pabi_purchase_work_acceptance/models/purchase_work_acceptance.py, pabi_purchase_work_acceptance/views/account_invoice_view.xml, pabi_purchase_work_acceptance/wizard/create_purchase_work_acceptance.py, pabi_purchase_work_acceptance/wizard/po_line_invoice.py
เพิ่มปุ่ม edit fiscalyear ที่ Tab Budget ใน Purchase Order
กรณีที่มีการทำ invoice plan และตั้งหนี้ผิดปี
โดยกลุ่มที่จะมีสิทธิ์เห็นปุ่ม edit นี้คือ group_budget_trans_manager (Transition Manager)
วิธีการใช้งานคือ เมื่อเกิดทำตั้งหนี้ผิดปี
1. แก้ไข fiscalyear ใน budgeting line ที่ทำผิดปี ให้เป็นปีที่ต้องการให้ระบบ commit budget ใหม่
deployment : restart and update module
- pabi_purchase_work_acceptance
- pabi_purchase_billing
- account_budget_activity 
============depend==============
- pabi_budget_monitor
- pabi_budget_plan_monitor
- pabi_etl
=> #4905 [FIX] po line fy
