hr_expense_auto_invoice/models/hr_expense.py

add analytic account in expense to create invoice.

[IMP] analytic accnount from exp to inv

---

pabi_procurement/models/purchase.py
pabi_procurement/views/purchase_master_data_view.xml

purchase commitee type's pr web method shoud be one2many with sequence

Enhance pabi_procusement

---

payment_export/models/account_bank.py

We no longer use this, as we can hard code bank account in tempalte

Remove checking that bank account to journal is 1-1

---

payment_export/models/account_voucher.py
payment_export/models/payment_export.py
payment_export/wizard/export_parser.py

[IMP] add validate account.voucher

---

pabi_budget_plan/models/__init__.py
pabi_budget_plan/models/pabi_xls.py
pabi_budget_plan/wizard/budget_breakdown_action_excel_import_wizard.py

[IMP] add import file

---

pabi_account_cheque/__init__.py
pabi_account_cheque/__openerp__.py
pabi_account_cheque/data/account_data.xml
pabi_account_cheque/jrxml_reports/supplier_payment_bbl_cheque.jrxml
pabi_account_cheque/jrxml_reports/supplier_payment_ktb_cheque.jrxml
pabi_account_cheque/models/__init__.py
pabi_account_cheque/models/account_voucher.py

P'Nuii please review my code (print cheque only supplier payment)
if ready please merge.
ref : https://mobileapp.nstda.or.th/redmine/issues/1716

[ADD] Add print cheque supplier payment

---

pabi_asset_management/models/account_move.py
pabi_asset_management/models/asset.py
pabi_asset_management/views/asset_transfer_view.xml
pabi_asset_management/views/asset_view.xml
pabi_asset_management/wizard/stock_transfer_details.py
pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
pabi_purchase_work_acceptance/wizard/create_purchase_work_acceptance.py
pabi_purchase_work_acceptance/wizard/create_purchase_work_acceptance_view.xml

* installment
* num_installment

2 new fields in WA and Asset

---

pabi_advance_dunning_letter/data/report_data.xml

Remove Download Filename

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

Remove all notice in the expense.

Add feature unlink dunning letter

---

pabi__actions/models/hr_expense.py

[ADD] add journal_id and operating_unit in account.voucher

---

pabi_advance_dunning_letter/models/__init__.py
pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py
pabi_advance_dunning_letter/models/res_company.py
pabi_apps_config/__openerp__.py
pabi_apps_config/models/pabi_apps_config.py
pabi_apps_config/views/pabi_apps_config.xml

[IMP] Add send mail to advance employee and supervisor

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

[IMP] Adjust to and cc mail

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

I'm editing to_employee_ids for due type 1, please merge.

[BUG] Adjust to_employee_ids for due type 1

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

[IMP] Add reply-to email (group email)

---

l10n_th_account_pnd_form/report/report_pnd53_form_xls.jrxml

[ADD] Add PND53 XLS

---

l10n_th_account/report/withholding_cert.jrxml

Adjust format date

---

pabi_long_term_investment_report/__init__.py
pabi_long_term_investment_report/__openerp__.py
pabi_long_term_investment_report/reports/__init__.py
pabi_long_term_investment_report/reports/pabi_long_term_investment_report.py
pabi_long_term_investment_report/reports/pabi_long_term_investment_report_xls.py
pabi_long_term_investment_report/wizards/__init__.py
pabi_long_term_investment_report/wizards/pabi_long_term_investment_report_wizard.py
pabi_long_term_investment_report/wizards/pabi_long_term_investment_report_wizard.xml

[IMP] Adjust Report

---

pabi_long_term_investment_report/reports/pabi_long_term_investment_report_xls.py

[IMP] Change invoice date value

---

pabi_account_financial_report_webkit/report/common_balance_reports.py

P'Nuii
Please check and merge.

[IMP] Add exclude type view trial balance

---

pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

[IMP] Adjust total formula

---

pabi_account_financial_report_webkit_xls/report/trial_balance_xls.py

P'Nuii
Please check and merge.

[IMP] Add total amount

---

pabi_advance_dunning_letter/report/advance_dunning_letter.jrxml
pabi_advance_dunning_letter/report/pabi_dunning_letter.jrxml

[IMP] Adjust Text Wrap

---

pabi_forms/jrxml_reports/account/adjustment_voucher.jrxml
pabi_forms/jrxml_reports/account/bank_receipt_voucher.jrxml
pabi_forms/jrxml_reports/account/invoice_voucher.jrxml
pabi_forms/jrxml_reports/account/payment_voucher.jrxml
pabi_forms/jrxml_reports/account/receipt_voucher.jrxml

P'Nuii please merge
>> https://mobileapp.nstda.or.th/redmine/issues/1827

[IMP] Adjust payment voucher form

---

pabi_forms/data/account_data.xml
pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml
pabi_forms/print_account_voucher/print_account_voucher_wizard.py

P'Nuii please check and merge krub
https://mobileapp.nstda.or.th/redmine/issues/1651

[IMP] Add Customer Receipt Form

---

pabi_forms/__init__.py
pabi_forms/__openerp__.py
pabi_forms/models/account_voucher.py
pabi_forms/print_payment_cheque/__init__.py
pabi_forms/print_payment_cheque/print_payment_cheque_parser.py
pabi_forms/print_payment_cheque/print_payment_cheque_wizard.py
pabi_forms/print_payment_cheque/print_payment_cheque_wizard.xml

please review and notify to improve.

[ADD] groups forms print cheque

---

pabi_partner_dunning_report/views/pabi_partner_dunning_letter_view.xml

P'Nuii please merge
It's this issue >> https://mobileapp.nstda.or.th/redmine/issues/1870

[IMP] Add search by partner

---

pabi_partner_dunning_report/report/pabi_customer_dunning_letter_en.jrxml
pabi_partner_dunning_report/report/pabi_customer_dunning_letter_th.jrxml

[FIX] reset amount by groupID

---

pabi_forms/qweb_reports/account/layouts.xml

P'Nuii please check and merge
https://mobileapp.nstda.or.th/redmine/issues/1879

Imp pk pabi forms adjust jn voucher

---

pabi_account/models/account_invoice.py
pabi_forms/data/account_data.xml
pabi_forms/jrxml_reports/account/customer_receipt.jrxml
pabi_forms/jrxml_reports/account/customer_tax_receipt.jrxml
pabi_forms/jrxml_reports/account/customer_tax_receipt_200.jrxml

P'Nuii Please check and merge krub
https://mobileapp.nstda.or.th/redmine/issues/1882

[IMP] Adjust Receipt Forms

---

pabi_budget_summary_report/__init__.py
pabi_budget_summary_report/__openerp__.py
pabi_budget_summary_report/reports/__init__.py
pabi_budget_summary_report/reports/budget_summary_report.py
pabi_budget_summary_report/reports/budget_summary_report_xls.py
pabi_budget_summary_report/security/ir.model.access.csv
pabi_budget_summary_report/wizards/__init__.py
pabi_budget_summary_report/wizards/budget_summary_action_excel_export_wizard.py
pabi_budget_summary_report/wizards/budget_summary_action_excel_export_wizard.xml

P'Nuii please review krub
https://mobileapp.nstda.or.th/redmine/issues/1890

[ADD] Add Budget Summary Report

---

pabi_budget_report/__openerp__.py

[IMP] Change data dict on openerp

---

pabi_budget_report/reports/budget_plan_analysis_report_xls.py

[IMP] Add previous_year_commitment value

---

pabi_async_process/__init__.py
pabi_async_process/__openerp__.py
pabi_async_process/action_generate_budget_plans/__init__.py
pabi_async_process/action_generate_budget_plans/generate_budget_plan_wizard.py
pabi_async_process/action_generate_budget_plans/generate_budget_plan_wizard.xml

P'Nuii please review krub (async process generate budget plans).

[ADD] Add action_generate_budget_plans

---

pabi_forms/qweb_reports/account/layouts.xml

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1956

[IMP] Adjust salary expense report

---

pabi_budget_report/reports/budget_plan_project_analysis_report_xls.py
pabi_budget_report/reports/budget_plan_unit_analysis_report_xls.py

P'Nuii please merge krub.
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1953

[IMP] Add Column Section Program

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/views/account_move_priority_view.xml
pabi_account_move_adjustment/wizard/account_move_change_date_due.py
pabi_hr_expense/models/hr_expense.py
pabi_hr_expense/views/hr_expense_view.xml
pabi_hr_expense/wizard/hr_expense_change_advance_date_due.py

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1971

[IMP] Add old due date in due history tab

---

pabi_bank_statement_reconcile/xlsx_template/xlsx_template_wizard.xml
pabi_budget_plan/xlsx_template/xlsx_template_wizard.xml
pabi_trial_balance_extension/xlsx_template/xlsx_template_wizard.xml

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1964

[IMP] Set export template to thai language

---

pabi_forms/__openerp__.py
pabi_forms/data/cheque_data.xml
pabi_forms/jrxml_reports/cheque/bay_cheque.jrxml
pabi_forms/jrxml_reports/cheque/scb_cheque.jrxml
pabi_forms/print_payment_cheque/print_payment_cheque_wizard.py
pabi_forms/print_payment_cheque/print_payment_cheque_wizard.xml

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1977

[IMP] Add cheque data

---

pabi_user_profile/views/hr_employee_view.xml

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/1973

[IMP] Add search by org and section in employee page

---

l10n_th_account_pnd_form/report/report_pnd3_form_xls.jrxml
l10n_th_account_pnd_form/report/report_pnd3a_form_xls.jrxml
l10n_th_account_pnd_form/report/report_pnd53_form_xls.jrxml
pabi_account_report/reports/xlsx_report_cheque_register.py

[IMP] Adjust pnd form

---

payment_export/views/cheque_lot_view.xml

[IMP] Add more search

---

pabi_account_report/__openerp__.py
pabi_account_report/data/report_data.xml
pabi_account_report/reports/__init__.py
pabi_account_report/reports/jasper_report_payable_confirmation_letter.jrxml
pabi_account_report/reports/jasper_report_payable_confirmation_letter.py
pabi_account_report/reports/jasper_report_payable_confirmation_letter.xml
pabi_account_report/reports/jasper_report_payable_confirmation_letter_parser.py
pabi_account_report/reports/report_account_common.py
pabi_account_report/reports/report_account_common.xml
pabi_account_report/reports/xlsx_report_partner_detail.py
pabi_purchase_billing/models/account_invoice.py
pabi_purchase_billing/models/purchase_billing.py

Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/2091

[IMP] Add payable confirmation letter report

---

pabi_account_report/__openerp__.py
pabi_account_report/data/report_data.xml
pabi_account_report/reports/__init__.py
pabi_account_report/reports/jasper_report_parser.py
pabi_account_report/reports/jasper_report_receivable_follow_up.py
pabi_account_report/reports/jasper_report_receivable_follow_up.xml
pabi_account_report/reports/jasper_report_receivable_follow_up_bank.jrxml
pabi_account_report/reports/jasper_report_receivable_follow_up_customer.jrxml
pabi_account_report/reports/report_account_common.py

P'Nuii please review krub
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/2106

[IMP] Add receivable follow up report

---

pabi_account_report/reports/xlsx_report_input_tax.py
pabi_account_report/reports/xlsx_report_input_tax.xml
pabi_account_report/reports/xlsx_report_output_tax.py
pabi_account_report/reports/xlsx_report_output_tax.xml
pabi_account_report/xlsx_template/templates.xml
pabi_th_tax_report/report/account_tax_report.py

[IMP] Adjust Tax Report

---

pabi_account_financial_report_webkit/report/common_reports.py
pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py
pabi_account_report/reports/xlsx_report_gl_allowance_doubtful_accounts.py
pabi_account_report/reports/xlsx_report_gl_allowance_doubtful_accounts.xml

-Edit and add column in report excel GL webkit
-Add condition reconcile_id is not null in allowance doubful report
-change menu allowance doubful from 'receivable menu' to 'gl menu'

[EDIT] column in report excel GL webkit 18/07/2018

---

pabi_ldap_syncuser/__openerp__.py

[fix] edit depends on module 'pabi_ldap'

---

pabi_budget_drilldown_report/models/budget_drilldown_report.py

Edit budget_drilldown report is not show 'amount_total_commit'

---

pabi_account_financial_report_webkit/report/common_reports.py
pabi_account_financial_report_webkit/report/general_ledger.py
pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

[ADD] col.Reconcile in Excel and hide reconcile when filter open_items

---

pabi_apps_config/views/pabi_menu_config.xml

[IMP] Add supplier menu under purchase menu

---

disable_about_odoo/__openerp__.py
disable_about_odoo/static/src/xml/base.xml
disable_about_odoo/views/res_user_view.xml

https://mobileapp.nstda.or.th/redmine/issues/2359

[IMP] Hide My Odoo.com account, Help and readonly all field in preference except language

---

l10n_th_account/models/account_wht_cert.py
l10n_th_account/views/account_wht_cert.xml

p'nuii please review krub.
https://mobileapp.nstda.or.th/redmine/issues/2370

[IMP] Add calendar period in wht cert

---

pabi_purchase_billing/__openerp__.py
pabi_purchase_billing/models/purchase_billing.py
pabi_purchase_billing/views/billing_date.xml
pabi_readonly_group/models/common.py

-Hide button
-Add tracking billing_sent_date

Fix onchange message 23/08/2018

---

pabi_forms/jrxml_reports/cheque/bay_cheque.jrxml
pabi_forms/jrxml_reports/cheque/bbl_cheque.jrxml
pabi_forms/jrxml_reports/cheque/ktb_cheque.jrxml
pabi_forms/jrxml_reports/cheque/scb_cheque.jrxml

-delete partner code
-fix bud is name partner too long

[FIX] print cheque form 4 bank (Supplier payment)

---

pabi_account/views/account_view.xml
payment_export/models/payment_export.py
payment_export/views/payment_export_view.xml

p'nuii please review krub.
https://mobileapp.nstda.or.th/redmine/issues/2315
https://mobileapp.nstda.or.th/redmine/issues/2373

[IMP] Add field in list view of bank journal

---

pabi_account/models/res_partner.py
pabi_account/views/res_partner_view.xml

p'nuii please review krub.
https://mobileapp.nstda.or.th/redmine/issues/2384

[IMP] Adjust button on corner right of partner

---

pabi_asset_management/models/asset.py
pabi_asset_management/views/asset_view.xml
z_migration/__openerp__.py
z_migration/models/__init__.py
z_migration/models/stock.py
z_migration/views/stock_view.xml

Net Book Value
https://mobileapp.nstda.or.th/redmine/issues/2488
No Jornal Entry
https://mobileapp.nstda.or.th/redmine/issues/2487

[IMP] Add net book value in asset

---

pabi_account/__openerp__.py
pabi_account/wizard/account_debitnote_view.xml
pabi_account/wizard/account_invoice_refund_view.xml
pabi_account_financial_report_webkit/report/templates/account_report_general_ledger.mako
pabi_account_report/reports/report_account_common.xml
pabi_apps_config/views/pabi_apps_config.xml
z_migration/__openerp__.py
z_migration/data/my_project_release_budget.csv
z_migration/models/__init__.py
z_migration/models/res_project.py
z_migration/scripts/myproject/myproject_act_release_budget.py

This issue consisted of
1. Script release budget my project
2. Change label long term investment https://mobileapp.nstda.or.th/redmine/issues/2491
3. Adjust activity group and activity in GL pdf https://mobileapp.nstda.or.th/redmine/issues/2492
4. Adjust domain period in criteria account report
5. Remove widget="selection" in refund and debitnote wizard

[IMP] Add script release budget my project

---

z_migration/__openerp__.py
z_migration/manual_script.txt
z_migration/models/__init__.py
z_migration/models/account_invoice.py
z_migration/models/account_voucher.py
z_migration/scripts/account_invoice/account_invoice_act_validate.py
z_migration/scripts/account_voucher/account_voucher_act_validate.py

This issue consisted of
1. script valudate invoice
2. script validate voucher

[IMP] Add additional script

---

z_migration/models/account_invoice.py
z_migration/scripts/account_invoice/account_invoice_act_validate.py

This issue consisted of
1. Update tax on invoice page

[IMP] Adjust script

---

pabi_budget_drilldown_report/__openerp__.py
pabi_budget_drilldown_report/models/__init__.py
pabi_budget_drilldown_report/models/analytic.py
pabi_budget_drilldown_report/models/budget_drilldown_report.py
pabi_budget_drilldown_report/views/analytic_view.xml
pabi_chartfield/models/analytic.py

p'nuii please review krub.
https://mobileapp.nstda.or.th/redmine/issues/2494

[IMP] Adjust budget drilldown report view

---

pabi_forms/print_account_voucher/print_account_voucher_wizard.py

Reference PR >> https://github.com/pabi2/pb2_addons/pull/702

[IMP] Remove block net payment form from supplier payment

---

account_trial_balance_report/models/trial_balance_report.py

Remove parameter moves and set state is posted in function _get_init_moves and _get_focus_moves

[IMP] Adjust trial balance (web)

---

pabi_interface/__openerp__.py
pabi_interface/views/account_view.xml

Show system origin in journal entry.

[IMP] Add system in journal entry

---

pabi_purchase_billing/models/account_invoice.py
pabi_purchase_invoice_plan/models/purchase.py
pabi_purchase_invoice_plan/wizard/purchase_create_invoice_plan.py

this issue for
1. recreate invoice doesn't block for case billing receipt date < current date
2. invoice plan can't create plan as fiscal year not in bound of order line

[IMP] Adjust Invoice Plan

---

pabi_budget_monitor/__openerp__.py
pabi_budget_monitor/models/purchase.py
pabi_budget_monitor/views/purchase_view.xml
z_migration/sql_utils/find_po_budget_problem.sql

@Pod, this one is safe to merge and deploy.

[ENH] pabi_budget_monitor, filter for POs with budget problem

---

pabi_budget_internal_charge/views/hr_expense_view.xml
pabi_budget_internal_charge/workflow/hr_expense_workflow.xml

This issue https://mobileapp.nstda.or.th/redmine/issues/2646
please review krub.

[IMP] Add access right reject button in expense with internal charge group

---

l10n_th_doctype_reversal/__openerp__.py
l10n_th_doctype_reversal/data/doctype_data.xml
l10n_th_doctype_reversal/models/__init__.py
l10n_th_doctype_reversal/models/account_bank_receipt.py

P'nuii plrase review krub.
https://mobileapp.nstda.or.th/redmine/issues/2678

[IMP] Adjust number cancel move of RV

---

pabi_bank_statement_reconcile/models/pabi_bank_statement.py
pabi_bank_statement_reconcile/views/pabi_bank_statement_view.xml

https://mobileapp.nstda.or.th/redmine/issues/2741

[IMP] Disable create and add notification message

---

pabi_procurement/__openerp__.py
pabi_procurement/views/purchase_view.xml
pabi_procurement/wizard/__init__.py
pabi_procurement/wizard/edit_purchase_desc.py
pabi_procurement/wizard/edit_purchase_desc_view.xml

Ref PR >> https://mobileapp.nstda.or.th/redmine/issues/2756

[IMP] Add card for edit description in PO Line

---

pabi_budget_plan/__openerp__.py
pabi_budget_plan/wizard/__init__.py
pabi_budget_plan/wizard/generate_asset_code.py
pabi_budget_plan/wizard/generate_asset_code_wizard.xml

Issue >> https://mobileapp.nstda.or.th/redmine/issues/2758

[IMP] Add generate asset code

---

pabi_stock_easy_internal_transfer/models/stock.py
pabi_stock_easy_internal_transfer/views/stock_view.xml

issue >> https://mobileapp.nstda.or.th/redmine/issues/2786

[IMP] Add readonly_picking_type_id

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/wizard/create_journal_entry_wizard.py

issues >> https://mobileapp.nstda.or.th/redmine/issues/2726

[Fix] Fix create adjustment journal of finlease

---

pabi_account/views/account_view.xml
pabi_procurement/views/purchase_view.xml
pabi_purchase_work_acceptance/views/purchase_view.xml
pabi_readonly_group/models/common.py

issue >> https://mobileapp.nstda.or.th/redmine/issues/2987

[IMP] Add always_show in smart button of purchase order

---

l10n_th_account_pit/views/res_partner_view.xml

issue >> https://mobileapp.nstda.or.th/redmine/issues/3048

PIT can click post manual

---

pabi_partner_dunning_report/models/pabi_partner_dunning_report.py
pabi_partner_dunning_report/report/layouts.xml
pabi_partner_dunning_report/report/qweb_report_customer_dunning_letter_template.xml

issue >> https://mobileapp.nstda.or.th/redmine/issues/2887

[FIX] change validator and adjust form

---

pabi_account_report/xlsx_template/templates.xml

issue >> https://mobileapp.nstda.or.th/redmine/issues/3079
Please update pabi_account_report in production and test

[IMP] Change selection income tax form in partner detail report

---

account_budget_activity/models/budget_transition.py
account_budget_activity/models/purchase.py
account_budget_activity/views/purchase_view.xml

To Update:
- account_budget_activity (only this module is changed)
- pabi_budget_monitor, pabi_budget_plan_monitor, pabi_etl (because above module is updated)
- pabi_apps_config
@kanokratps ปอลงเคสนี้ให้พี่เมย์ทดสอบที่ Test ก่อนครับ แล้วค่อยลงต่อที่ Production

[ENH] account_budget_activity, add new remove po line button

---

pabi_forms/qweb_reports/account/adjustment_voucher.xml
pabi_forms/qweb_reports/account/bank_receipt_voucher.xml
pabi_forms/qweb_reports/account/interface_account_voucher.xml
pabi_forms/qweb_reports/account/invoice_voucher.xml
pabi_forms/qweb_reports/account/layouts.xml
pabi_forms/qweb_reports/account/payment_voucher.xml
pabi_forms/qweb_reports/account/receipt_voucher.xml
pabi_forms/qweb_reports/account/salary_expense_voucher.xml

Update module
- pabi_forms
Not Restart

[FIX] position dr, cr in account_voucher form

---

account_budget_activity/report/budget_consume_report.py
account_budget_activity/report/budget_monitor_report.py
account_budget_activity/report/budget_plan_report.py

To Update:
- **account_budget_activity**
- budget_plan_monitor, pabi_budget_plan_monitor, pabi_etl
- pabi_apps_config
:100755 100755 b5dfcafe d78b127e M	account_budget_activity/report/budget_consume_report.py
:100755 100755 8b452945 5a6a87d8 M	account_budget_activity/report/budget_monitor_report.py
:100755 100755 7080f71f ac17baf2 M	account_budget_activity/report/budget_plan_report.py

[ENH] account_budget_activity, tuning slow view, budget_monitor_report

---

pabi_asset_management/models/asset_changeowner.py
pabi_asset_management/views/asset_changeowner_view.xml

เพิ่มปุ่ม รัน change owner แบบ background

ADD button Change Owner background process

---

account_model_purchase_invoice_plan/views/account_view.xml
pabi_account_move_adjustment/views/account_view.xml
pabi_account_move_document_ref/views/account_view.xml
pabi_hr_expense/views/hr_expense_view.xml

ฝากพี่ปอตรวจสอบแล้ว merge code ด้วยครับ
4 files within 1. acc_model_pur_in_plan 2. pabi_acc_move_doc_ref 3. pabi_acc_move_adj 4. pabi_hr_exp

insert fields within pabi2_addon

---

hr_expense_advance_clearing/models/hr_expense.py
pabi_hr_advance_clearing_followup_report/report/advance_clearing_followup_report.py

Please restart and update on test and production server.
** update
- hr_expense_advance_clearing
- pabi_hr_advance_clearing_followup_report
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/3094

[IMP] Adjust performance run advance clearing followup

---

account_budget_activity/models/budget_commit.py

มีการเรียก api ใช้งานจาก script จำเป็นต้องมีการ return ออกจาก function ครับ

fix script error call api function release_all_committed_budget

---

hr_expense_advance_clearing/views/hr_expense_view.xml

Please merge, deploy and update
- hr_expense_advance_clearing

[IMP] hide create, edit and delete from hr.expense.clearing

---

pabi_account_move_document_ref/views/account_view.xml
pabi_account_report/reports/xlsx_report_expense_ledger.xml

P.Por ครับ
edit 2 model pabi2_addons
1.pabi_acc_move_doc_ref/view/acc_view.xml ลบฟิล
2.pabi_acc_rep/rep/xls_rep_exp_ledg.xml แก้ไข domain

ลบ field และ แก้ไข domain

---

pabi_partner_dunning_report/report/layouts.xml

Please merge, deploy and update
- pabi_partner_dunning_report
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/2887

[IMP] Change format partner address

---

pabi_account_report/reports/jasper_report_cd_receivable_follow_up_group_by_bank.jrxml
pabi_account_report/reports/jasper_report_cd_receivable_follow_up_group_by_customer.jrxml
pabi_account_report/reports/jasper_report_cd_receivable_payment_history_group_by_bank.jrxml
pabi_account_report/reports/jasper_report_cd_receivable_payment_history_group_by_customer.jrxml

Please deploy only, this issue no restart, no update
Ref issues
https://mobileapp.nstda.or.th/redmine/issues/3117

[FIX] fix period grace day is null

---

pabi_budget_drilldown_report/models/common.py
pabi_budget_drilldown_report/views/budget_drilldown_common.xml
pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.py
pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml

Please merge, deploy, restart and update on test and production server.
- pabi_budget_drilldown_report
Ref issue >.> https://mobileapp.nstda.or.th/redmine/issues/2882

[FIX] budget overview filter groupby

---

pabi_account/__openerp__.py
pabi_account/models/account_voucher.py
pabi_account/views/account_voucher_view.xml
pabi_account/wizard/__init__.py
pabi_account/wizard/voucher_loan_agreement_description.py
pabi_account/wizard/voucher_loan_agreement_description_view.xml
pabi_forms/jrxml_reports/account/customer_receipt.jrxml

Please merge, deploy, restart and update on server test first, if it's test pass you can deploy on production
- pabi_account
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/3108

[IMP] Adjust customer receipt form

---

pabi_account/models/account_voucher.py

P.Por Check and Merge 1 method in pab2_addons/pabi_acc/models/account_voucher.py

Close _check_date_value_same_period method

---

res_partner_ext/models/partner_interface.py

P.Por Test ja 1 method in pabi2_addons/res_partner/models/partner_interface.py

เพิ่มการเรียกใช้ฟังชั่นใน res.partner

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

Please deploy, no restart and no update
Ref issue >> https://mobileapp.nstda.or.th/redmine/issues/3108

[Fix] Fix customer receipt form

---

pabi_report_balance_sheet_xls/report/balance_sheet_xls.py

please deploy and restart, no update
**No issue, it's bug balance sheet and profit & loss report**

[FIX] Fix balance sheet and profit & loss report

---

pabi_account_move_adjustment/__openerp__.py
pabi_account_move_adjustment/wizard/account_move_reverse.py
pabi_account_move_adjustment/wizard/account_move_reverse_view.xml

เพิ่มปุ่ม Reverse Entries แบบ bankground

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

P.Por ครับ merge ให้ทีครับ
1 file: pb2_addons/pabi_forms/jrxml_reports/account/customer_recript.jrxnl

เพิ่ม field ใน report receipt

---

hr_expense_auto_invoice/models/hr_expense.py

FIX ปัญหาปรับโครงสร้าง หลักจากกด Create Supplier Invoice

---

hr_expense_auto_invoice/models/hr_expense.py

fix change if len invoice to line

---

pabi_account_move_adjustment/wizard/account_move_reverse.py
pabi_account_move_adjustment/wizard/account_move_reverse_view.xml

deploy test 
ซ่อนฟิว debug ที่ใช้สำหรัปุ่ม Reverse Entries แบบ Background
และปิดการใช้งานปุ่ม Reverse Entries(Background)

Jakkrich.cha add btn reverse background

---

pabi_asset_management/models/asset_changeowner.py

write log ดูการทำงานของ changeowner ว่ากำลังทำงานอยู่

---

pabi_account/models/account_move_line.py

Deploy Step:
update -> pabi_account, pabi_apps_config

[FIX] 3152 fix wrong budget actual on cancel invoice

---

pabi_asset_management/models/asset_changeowner.py
pabi_asset_management/views/asset_changeowner_view.xml

Jakkrich.cha button job sync changeowner

---

pabi_asset_management/models/asset_changeowner.py

ตัด default

---

pabi_async_process/pabi_action_asset_compute/pabi_action_asset_compute.py

Bug #3162 Block การ Run ค่าเสื่อมราคาเบิ้ล 
เมนู Accounting -> Periodic Processing -> Recurring Entries -> Compute Assets
หลักการ
เมื่อกดปุ่ม Execute ให้ตรวจสอบ model = pabi.asset.depre.batch ต้องไม่มี state = Draft อยู่เลย
หากยังมี state = Draft ให้แสดง Error ออกมา

#3162 tangkwa

---

pabi_account_report/reports/xlsx_report_pit_detail.py
pabi_account_report/xlsx_template/templates.xml

P.Por ครับ Merge ให้ทีครับ
แก้ไขข้อมูลที่ Export ออกมา
modules: NSTDA :: Accounting Reports

#3144 แก้ไขการ Export ข้อมูลของ PIT Report

---

hr_expense_auto_invoice/models/hr_expense.py

แก้ปัญหา create_supplier_invoice ตอน validate inv.
เกิดจากการ stamp ค่าไม่ครบ

fix create_supplier_invoice validate inv. stamp ฟิวเพิ่ม

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

module /pb2_addons/pabi_advance_dunning_letter
แก้ domain fields dunning_list_*

#3147 Advance Dunning Letter

---

pabi_import_journal_entries/models/pabi_import_journal_entries.py
pabi_import_journal_entries/views/pabi_import_journal_entries_view.xml

P.Por ครับ เอาขึ้น test ให้ทีครับ
modules - pb2_addons/pabi_import_journal_entries : NSTDA :: PABI2 - Bulk Import Journal Entries
เมื่อกดปุ่ม จะเรียกปุ่ม split_entries ไปทำงานหลังบ้าน(job)

#3170 - เพิ่มปุ่ม split_entries Job background 

---

pabi_async_process/pabi_action_asset_compute/pabi_action_asset_compute.py

Block การ Run ค่าเสื่อมราคาเบิ้ล(โค้ดใหม่)
เมนู Accounting -> Periodic Processing -> Recurring Entries -> Compute Assets
หลักการ
เมื่อกดปุ่ม Execute ให้ตรวจสอบ model = pabi.asset.depre.batch ต้องไม่มี state = Draft อยู่เลย
หากยังมี state = Draft ให้แสดง Error ออกมา

#3162 Block การ Run ค่าเสื่อมราคาเบิ้ล โค้ดใหม่

---

pabi_import_journal_entries/models/pabi_import_journal_entries.py

#3170 - ปรับเปลี่ยนชื่อ Description ตอนกดใช้ปุ่ม split entries job
modules - pb2_addons/pabi_import_journal_entries : NSTDA :: PABI2 - Bulk Import Journal Entries

#3170 - ปรับเปลี่ยนชื่อ Description ตอนกดใช้ปุ่ม split entries job

---

payment_export/models/cheque_lot.py
payment_export/views/cheque_lot_view.xml

P.Por ครับ merge ให้ทีครับ
Modules - pb2_addons/payment_export : Payment Export Pack
เพิ่ม fields Posting date และ Period

#3172 - Cheque Register เพิ่ม fields 

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

#3131 - แก้ไขไฟล์ในการอ่าน jasper reports ของ  Receipt Report ให้สามารถใช้งานใน pabi2 ได้
Modules - pb2_addons/pabi_forms : NSTDA :: PABI2 - Forms

#3131 - Receipt Report in Customer Payments

---

pabi_budget_monitor/report/budget_monitor_report_wizard_view.xml

#3171 รายงาน Budget monitoring ให้เพิ่ม Section ที่ Inactive ใน List Section
ที่เมนู Budgeting >> Budget Monitor >> Budget Monitoring
• ปรับเงื่อนไขการแสดง Section List ใน Filter ให้แสดงสถานะที่เป็น Active = False
• ใน List เมื่อกรอก Section ที่ Active = False ให้แสดง Section ที่ช่อง Print Only

#3171 รายงาน Budget monitoring ให้เพิ่ม Section ที่ Inactive ใน List

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

#3131 - แก้ไข field ธนาคารใน Receipt Report ออก
modules - pb2_addons/pabi_forms : NSTDA :: PABI2 - Forms

#3131 - Receipt Report

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

P.Por ครับ ตัวใหม่ครับ test ให้ทีครับ
#3131 - เพิ่ม domain ในการแสดงชื่อธนาคารใน Receipt Report
Modules - pb2_addons/pabi_forms : NSTDA :: PABI2 - Forms

#3131 - เพิ่ม domain ในการแสดงชื่อธนาคารใน Receipt Report

---

payment_export/models/account_voucher.py
payment_export/views/voucher_payment_receipt_view.xml

module: payment_export
เพิ่ม field Cheque encashment date ในหน้า PV

#3181-cheque_encashment

---

pabi_account_report/reports/xlsx_report_expense_ledger.xml
pabi_account_report/reports/xlsx_report_revenue_ledger.py
pabi_account_report/reports/xlsx_report_revenue_ledger.xml

#3178 - เพิ่มข้อมูล GL ใน Expense Ledger และเพิ่ม Org ใน Revenue Ledger
Modules - pb2_addons/pabi_account_report : NSTDA :: Accounting Reports

#3178 - เพิ่มข้อมูล GL ใน Expense Ledger และเพิ่ม Org ใน Revenue Ledger

---

pabi_asset_management/wizard/account_asset_remove.py

P.Por Merge ให้ทีครับ
#3192 - แก้ไข Domain ของ Asset Remove
Modules - pb2_addons/pabi_asset_management : NSTDA :: PABI2 - Asset Management

#3192 - แก้ไข Domain ของ Asset Remove

---

pabi_chartfield_merged/models/chartfield.py

#3200 - modules - pb2_addons/pabi_chartfield_merged : NSTDA :: PABI2 Merged Chartfield to 1 column
แก้ไข domain chartfield ให้แสดงข้อมูลให้ครบถ้วนในหน้า Journal line

#3200 - แก้ไข domain - chartfield_id ที่ line_ids

---

pabi_asset_management/wizard/account_asset_remove.py

P.Por ครับ Merge ให้ทีครับ
Modules - pb2_addons/pabi_asset_management : NSTDA :: PABI2 - Asset Management

#3192 - แก้ไข Domain ของ Journal ใน Asset Form กลับคืนแบบเก่า

---

pabi_budget_drilldown_report/models/common.py

-เมนู Budgeting > Budget Report > My Budget Report 
ปรับเงื่อนไขการแสดง Section List ใน Filter ให้แสดงสถานะที่เป็น Active = False

#3198:MyBudgetReport ให้เพิ่ม Section ที่ Inactive ใน List Section

---

account_general_ledger_report/models/general_ledger_report.py
account_trial_balance_report/models/trial_balance_report.py

Issue - https://mobileapp.nstda.or.th/redmine/issues/3216
Deployment:
* Pull code for account_trial_balance_report
* Restart server, no update required

[FIX] account_trial_balance_report, wrong init for period 1 report

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

https://mobileapp.nstda.or.th/redmine/issues/3147#change-11529
module: pabi_advance_dunning_letter
***แก้ไข dmain fields date_dunning_*

#3147 advance dunning letter2

---

pabi_asset_management/data/asset_status.xml
pabi_asset_management/models/asset.py
pabi_asset_management/models/asset_adjust.py
pabi_asset_management/models/asset_removal.py
pabi_asset_management/wizard/account_asset_remove.py
pabi_asset_management/wizard/account_asset_reverse.py

ปรับ domain ที่ใช้ map_state ให้เป็นตัวใหม่
ปรับ เมื่อ state เป็น close จะไม่เปลี่ยน status เป็น expire แบบ auto
เพิ่ง validate state และ status ให้สอดคล้องกันตอน write

เพิ่มฟิล map_state_xxx ตามสถานะ

---

payment_export/models/cheque_lot.py
payment_export/views/cheque_lot_view.xml

เมนู Accouting > Payment Exports > Cheque Register 
1. เพิ่มฟิลด์ Update by (user_id )
2. เพิ่มฟิลด์ Update date (update_date)

#3228:FI: ขอเพิ่ม field หน้า Cheque Register

---

pabi_account_report/reports/xlsx_report_expense_ledger.py
pabi_account_report/reports/xlsx_report_expense_ledger.xml

P.Por merge ให้ทีครับ
Modules - /pabi_account_report : NSTDA :: Accounting Reports
เพิ่ม Org field เพื่อใช้ในการ search แยก domain ของ account_id และ partner_id

#3178 - Insert Org searching field in Expense_Ledger

---

z_migration/models/account.py

P.Por ครับ
Close line_item_summary field in z_migration
module - /z_migration/models/account.py : Migration Scripts

#3243 - Close field account.py in z_migration

---

pabi_asset_management/models/asset_removal.py
pabi_asset_management/wizard/account_asset_remove.py
pabi_asset_management/wizard/account_asset_reverse.py

fix error miss ]

---

pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

https://mobileapp.nstda.or.th/redmine/issues/3147#change-11529
module: pabi_advance_dunning_letter
***แก้ไข domain on due date

#3147-Advance_Dunning_Letter3

---

pabi_user_profile/__openerp__.py
pabi_user_profile/models/__init__.py
pabi_user_profile/models/hr_employee.py
pabi_user_profile/models/res_section.py
pabi_user_profile/views/hr_employee_view.xml
pabi_user_profile/views/res_section_view.xml

เพิ่มหน้าจอสำหรับกำหนดสิทธิ์การดูรายงานงบหน่วยงาน(Unit Base)
1.เมนู Configurations > Oragantization > Section Budget Structure > Section > เพิ่ม page Report
2. เมนู  Configurations > Human resources > Directory > Employees > เพิ่ม page Section Report

#3249_เพิ่มหน้าจอสำหรับกำหนดสิทธิ์การดูรายงานงบหน่วยงาน

---

pabi_account_report/reports/xlsx_report_advance_status.py

https://mobileapp.nstda.or.th/redmine/issues/3147#change-11635
module: pabi_account_report
**แก้ไข query ใน xlsx.report.advance.status

#3147-Advance_Dunning_Letter4

---

hr_expense_auto_invoice/models/hr_expense.py

FI : User สร้างเอกสาร EX เคลียร์เงินยืม แล้ว ระบบไม่หยอด Taxbranch_id มาให้

เปลี่ยนการเขียนวิธี update ใหม่

---

pabi_asset_management/data/asset_status.xml
pabi_asset_management/models/asset.py

[ADD] status[expire] at state[running] and not change status when update

---

pabi_account_report/reports/xlsx_report_advance_status.py
pabi_budget_drilldown_report/views/budget_project_base_report.xml
pabi_budget_drilldown_report/views/budget_unit_base_report.xml
pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml

https://mobileapp.nstda.or.th/redmine/issues/3238
module: pabi_budget_drilldown_report
***เพิ่ม Budget Method ในรายงาน My Budget Report

#3238-Budget_Method

---

pabi_account_report/reports/xlsx_report_advance_status.py
pabi_advance_dunning_letter/models/pabi_advance_dunning_letter.py

https://mobileapp.nstda.or.th/redmine/issues/3147#change-11635
module: pabi_advance_dunning_letter
**แก้ไข readonly fields date_print

#3147 advance dunning letter4

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/views/account_view.xml

P.Por เอาขึ้น test ให้ทีครับ
#3264 - insert post job button on Journal Adj.No.Budget
Modules - /pabi_account_move_adjustment : Account Move - Adjustment Types

#3264 - insert post job button on Journal Adj.No.Budget

---

pabi_asset_management/models/asset_transfer.py

P.Por merge ทีครับ
แก้ไข Domain ของ asset_ids ใน asset_transfer.py
Modules - /pabi_asset_management : NSTDA :: PABI2 - Asset Management

#3268 - change domain in asset_transfer.py

---

pabi_account_financial_report_webkit/wizard/general_ledger_wizard.py
pabi_account_financial_report_webkit/wizard/general_ledger_wizard_view.xml

รายงาน General Ledger เพิ่มเงื่อนไข Org
เมนู Accounting > Reporting> Legal Reports > Accouting Report > General Ledger

#3271 เพิ่มฟิลด์ org

---

pabi_account_move_adjustment/models/account.py

P.Por merge ให้ทีครับ
#3264 - insert import RedirectWarning
Modules - /pabi_account_move_adjustment : Account Move - Adjustment Types

#3264 - insert import RedirectWarning

---

pabi_account_move_adjustment/models/account.py

P.Por อัพขึ้น test ทีครับ แก้ไขนิดหน่อยครับ
#3264 - แก้ไขชื่อฟังชั่นเรียกใช้งานปุ่ม และชื่อ job
Modules - /pabi_account_move_adjustment : Account Move - Adjustment Types

#3264 - แก้ไขชื่อฟังชั่น และชื่อ job

---

pabi_account_financial_report_webkit/wizard/trial_balance_wizard.py
pabi_account_financial_report_webkit/wizard/trial_balance_wizard_view.xml

รายงาน Trial Balance เพิ่มเงื่อนไข Org.
เมนู Accounting > Reporting> Legal Reports > Accouting Report > Trial Balance

#3272: รายงาน Trial Balance เพิ่มเงื่อนไข Org.

---

purchase_cash_on_delivery/models/purchase.py

P.Por เอาขึ้น test ให้ทีครับ จะลอง test ดูครับ
#3250 - เช็คค่า sum ใน invoices กับ  PO บน purchase_cash_on_deliver
Modules - /purchase_cash_on_delivery : NSTDA :: PABI2 - Purchase Cash on Delivery

#3250 - chk_invoices in purchase_cash_on_deliver

---

pabi_asset_management/data/sequence_data.xml
pabi_asset_management/models/asset.py

P.Por ขึ้น Test ให้ทีครับ
Modules - /pabi_asset_management : NSTDA :: PABI2 - Asset Management

Change Parent Asset code in Parent Assets menu

---

pabi_account_report/reports/xlsx_report_advance_status.py

P.Por เอาขึ้น test ให้ทีครับ
Modules - /pabi_account_report : NSTDA :: Accounting Reports

#3281 - เพิ่ม domain ใน Advance Status report

---

pabi_account_report/__openerp__.py
pabi_account_report/data/status_data.xml
pabi_account_report/reports/__init__.py
pabi_account_report/reports/report_status.py
pabi_account_report/reports/xlsx_report_advance_status.py
pabi_account_report/reports/xlsx_report_advance_status.xml

#3281 - เพิ่ม status field ในการเลือกกรองข้อมูล export excel ใน Advance Status
P.Por ครับ merge แล้วเอาขึ้น test ให้ทีครับ
Modules - /pabi_account_report : NSTDA :: Accounting Reports

#3281 - เพิ่ม status field ใน Advance Status

---

pabi_account_financial_report_webkit/report/common_reports.py
pabi_account_financial_report_webkit/report/general_ledger.py
pabi_account_financial_report_webkit/report/templates/account_report_general_ledger.mako
pabi_account_financial_report_webkit/wizard/general_ledger_wizard.py
pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

เมนู Reporting> Legal Reports > Accouting Report > General Ledger
- เพิ่ม filter org ใน report

#3271 general ledger

---

pabi_purchase_invoice_plan/models/purchase.py
pabi_purchase_invoice_plan/views/purchase_view.xml

#3252 - เพิ่ม fields บน view form ใน invoice_plan ของหน้า purchase order
File - /pb2_addons/pabi_purchase_invoice_plan
Modules - NSTDA :: PABI2 - Purchase Invoice Plan

#3252 - insert fields ใน invoice_plan หน้า purchase order

---

pabi_interface/models/interface_account.py

เช็ค document origin ว่าห้ามซ้ำ
https://mobileapp.nstda.or.th/redmine/issues/3320

3320 interface check document origin

---

pabi_account_report/reports/xlsx_report_expense_ledger.py
pabi_account_report/reports/xlsx_report_revenue_ledger.py

#3294-#3295 - เพิ่ม domain active = true and active = false ของ Budget ใน expense ledger and revenue ledger report
Files - /pb2_addons/pabi_account_report
Modules name - NSTDA :: Accounting Reports

#3294-#3295 - add domain in expense ledger and revenue ledger report

---

payment_export/models/cheque_lot.py
payment_export/views/cheque_lot_view.xml

https://mobileapp.nstda.or.th/redmine/issues/3323
เพิ่ม field responsible หน้า View Cheque Register

#3323-Cheque_Register

---

pabi_account_report/reports/xlsx_report_expense_ledger.py
pabi_account_report/reports/xlsx_report_gl_project.py
pabi_account_report/reports/xlsx_report_gl_project.xml
pabi_account_report/reports/xlsx_report_revenue_ledger.py

#3294-#3295 - ปิด default ของ account_id.user_typ ใน Expense Ledger report และ Revenue Ledger report
File - /pb2_addons/pabi_account_report
Modules name - NSTDA :: Accounting Reports

#3294-#3295 - close default of account_id.user_typ in Expense Ledger and Revenue Ledger

---

account_general_ledger_report/models/general_ledger_report.py
account_general_ledger_report/views/general_ledger_report.xml
account_general_ledger_report/wizard/general_ledger_wizard.py
account_general_ledger_report/wizard/general_ledger_wizard.xml

เมนู Reporting> Legal Reports > General Ledger (Web)
- เพิ่มฟิลด์ org_ids 
- กรอง org_ids ใน account_move_line

#3273 gl web

---

account_trial_balance_report/models/trial_balance_report.py
account_trial_balance_report/views/trial_balance_report.xml
account_trial_balance_report/wizard/trial_balance_wizard.py
account_trial_balance_report/wizard/trial_balance_wizard.xml

เมนู Reporting> Legal Reports >Trial Balance (WEB)
1. เพิ่ม Org. และ Account ในหน้า view และ report
2. filter org และ account

#3274 Add Org and Account

---

payment_export/models/payment_export.py
payment_export/views/cheque_lot_view.xml

#3344 - #3346 - เพิ่ม fields ในหน้า treeview ของ Payment Export และ Cheque Register
File : /pb2_addons/payment_export
Modules_name : Payment Export Pack

#3344 - #3346 - insert fields on Payment Export and Cheque Register

---

pabi_account_financial_report_webkit/report/common_reports.py

เมนู Reporting> Legal Reports > Accouting Report > Trial Balance
- แก้ bug ค่า Initial Balance ไม่ขึ้น

#3272 Bug Initial Balance

---

pabi_account_financial_report_webkit_xls/report/trial_balance_xls.py

เมนู Reporting> Legal Reports > Accouting Report > Trial Balance
- เพิ่ม org ใน export

#3272 เพิ่ม org ใน export

---

pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

เมนู Reporting> Legal Reports > Accouting Report > General Ledger
- Bug Nonetype

#3271 Bug Nonetype

---

pabi_forms/jrxml_reports/procurement/call_for_bids_1.jrxml

#3343 - แก้ไข amount_total_th ในไฟล์ call_for_bids_1.jrxml ซึ่งเป็น jasper pdf
File - /pb2_addons/pabi_forms/jrxml_reports/procurement
Modules_name - NSTDA :: PABI2 - Forms

#3343 - edit call_for_bids_1 in jrxml_report

---

pabi_procurement_report/__openerp__.py
pabi_procurement_report/reports/__init__.py
pabi_procurement_report/reports/xlsx_report_pabi_stock_balance.py
pabi_procurement_report/reports/xlsx_report_pabi_stock_balance.xml
pabi_procurement_report/xlsx_template/load_template.xml
pabi_procurement_report/xlsx_template/templates.xml

#3360 - สร้าง report ใหม่ เพื่อแก้ไขทดสอบข้อมูลที่ export excel ของ Stock Balance 
File : /pb2_addons/pabi_procurement_report
Modules_name : NSTDA :: Procurement Report

#3360 - Create Stock_Balance_Test report for Test export excel

---

pabi_account/views/account_invoice_view.xml
purchase_invoice_plan/__openerp__.py
purchase_invoice_plan/models/account_invoice.py
purchase_invoice_plan/views/account_invoice_view.xml

เมนู Supplier Invoice 
1. เพิ่ม filler และ Group by Invoice Plan
2.เพิ่ม Document Date และ Installment

#3336 เพิ่ม Field ที่หน้า View Supplier Invoice

---

pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

เมนู Reporting> Legal Reports > Accouting Report > General Ledger
- test org_id

#3271 Test bug org_id pdf

---

pabi_account_report/reports/asset_register_report.py
pabi_account_report/reports/asset_register_report.xml

#3311 แก้ไขข้อมูลตอนกรองลง excel ใน Asset Register report
File : /pb2_addons/pabi_account_report
Modules_name : NSTDA :: Accounting Reports

#3311 edit excel export in Asset Register report

---

payment_export_text/wizard/export_parser.py

เปลี่ยนการ run code จาก eval() เป็น exec() ใน payment_export
File : /pb2_addons/payment_export_text
Modules_name : Payment Export Pack - Text

#3341 - change code eval() to exec() in payment_export

---

pabi_forms/jrxml_reports/account/customer_receipt.jrxml

#3302 body null

---

pabi_account_report/reports/asset_register_report.py
pabi_account_report/reports/asset_register_report.xml
pabi_account_report/security/ir.model.access.csv

File : /pb2_addons/pabi_account_report
Modules : pabi_account_report

#3311 - Edit export to Asset Register report

---

pabi_account_report/reports/asset_register_report.py
pabi_account_report/reports/asset_register_report.xml

#3311 - ตั้งค่า export excel ให้เป็นภาษาไทย
File : /pb2_addons/pabi_account_report
Modules : pabi_account_report

#3311 - Default Thai language on Asset Register report

---

pabi_purchase_invoice_plan/views/purchase_view.xml

#3387 - เพิ่มฟิลของ PO ที่เป็น Advance ใน Invoice Plan
File : /pb2_addons/pabi_purchase_invoice_plan
Modules : pabi_purchase_invoice_plan

#3387 - Insert fields in Advance Invoice Plan

---

pabi_forms/data/account_data.xml
pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml

#3400 - แก้ไขไฟล์ customer_receipt_voucher ที่เป็น Jasper report
File : /pb2_addons/pabi_forms
Modules : pabi_forms

#3400 - Edit customer_receipt_voucher

---

pabi_account_move_adjustment/views/account_move_priority_view.xml

#3418 - เพิ่มปุ่ม Post เป็น run background ในเมนู Journal Entries
File : /pb2_addons/pabi_account_move_adjustment
Modules : pabi_account_move_adjustment

#3418 - insert Post background button

---

pabi_partner_dunning_report/report/layouts.xml
pabi_partner_dunning_report/report/pabi_customer_dunning_letter_en.jrxml
pabi_partner_dunning_report/report/pabi_customer_dunning_letter_th.jrxml

https://mobileapp.nstda.or.th/redmine/issues/3427
module: pabi_partner_dunning_report
เปลี่ยนชื่อตัวย่อกระทรวง ของ จดหมายออก Dunning letter

#3427-Dunning_letter

---

pabi_purchase_invoice_plan/models/purchase.py

#3325 - แก้ไข Error ของปุ่ม Recreate_invoice บนเมนู Supplier Invoices
File - /pb2_addons/pabi_purchase_invoice_plan
Modules_name - NSTDA :: PABI2 - Purchase Invoice Plan

#3325 - Solve Error in Recreate_Invoice on Supplier Invoices menu

---

pabi_asset_management/models/asset_adjust.py
pabi_asset_management/wizard/create_asset_adjust_wizard.py

ปรับปรุงส่วนการ create adjustment asset
- ปรับปรุงส่วนของ AG&A ของเดิมให้ย้ายมาอยู่รายการ asset แล้วเอา AG&A ของ invoice มาใส่ในรายการค่าใช้จ่าย
- สร้าง analytic_line โดยเอารายละเอียดของ invoice มาสร้าง

3299 adjust expense to asset

---

account_budget_activity/models/analytic.py
pabi_asset_management/models/asset_adjust.py
pabi_asset_management/wizard/create_asset_adjust_wizard.py

#3456 debug adjust asj

---

account_unreconciled_filter/wizard/move_open_unreconciled_items.py
account_unreconciled_filter/wizard/move_open_unreconciled_items.xml

#3465 - แก้ไขการใส่ข้อมูลของ move_id field บน Open_Unreconclied
File : /pb2_addons/account_unreconciled_filter
Modules : account_unreconciled_filter

#3465 - Edit field type on Open_Unreconclied

---

pabi_account/models/account_voucher.py

เมนู Accounting > Loan installments > Loan installment
1. แก้ไข wording ใบเสร็จรับเงินจาก 
ยอดหนี้คงเหลือ --> เงินต้นคงเหลือ
2. แสดงเงินต้นคงเหลือไม่ถูก จริงๆ ต้องเป็น 35,786.91

#3471 report loan

---

pabi_account_move_adjustment/models/account.py
pabi_asset_management/models/account_move.py

https://mobileapp.nstda.or.th/redmine/issues/3433
https://mobileapp.nstda.or.th/redmine/issues/3369
แก้ไข Org/Budget/Cost Center/Fund
Module: pabi_account_move_adjustment,pabi_asset_management

#3433 stock pos

---

pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml

File : /pb2_addons/pabi_forms/jrxml_reports/account

#3491 - edit customer receipt voucher

---

pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

#3438 - edit Purchase_Order_th jasper
File : /pb2_addons/pabi_forms/jrxml_reports/procurement

#3480 - edit Purchase_Order_th jasper

---

pabi_account/models/account.py
pabi_account/views/account_view.xml
pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/views/account_move_priority_view.xml
pabi_account_move_adjustment/wizard/account_move_reverse.py

https://mobileapp.nstda.or.th/redmine/issues/3453
Module: pabi_account,pabi_account_move_adjustment

#3453-TPReverse

---

pabi_account_report/reports/xlsx_report_gl_project.py

เมนู Accounting > reports > General ledger > GL Project
- เพิ่ม vat บางช่องหาย

เพิ่ม VAT บางช่องหาย

---

pabi_budget_plan/xlsx_template/templates.xml

#3479 - update header
File : /pb2_addons/pabi_budget_plan
Module : pabi_budget_plan

#3479 - update header

---

pabi_invest_construction/views/invest_construction_view.xml

https://mobileapp.nstda.or.th/redmine/issues/3524
Module: pabi_invest_construction
เพิ่ม Role ของปุ่มใน form

#3524-ConstructionRole

---

payment_export_text/wizard/export_parser.py

#3509 - edit payment export
File : /pb2_addons/payment_export_text
Module : payment_export_text

#3509 - edit payment export

---

pabi_budget_plan_monitor/models/budget_plan_project.py
pabi_utils/wizard/export_xlsx_template.py
pabi_utils/wizard/export_xlsx_template_wizard.xml

Insert run background and edit Prev.FY Performance button
Files : /pb2_addons/pabi_budget_plan_monitor, /pb2_addons/pabi_utils
Modules : pabi_budget_plan_monitor, pabi_utils

#3492 unit based project

---

pabi_asset_management/wizard/account_asset_reverse.py

เวลายกเลิกครุภัณฑ์ ที่ PO > IN แล้วเลือก Asset ไปที่เมนู More > Void/removed asset ให้เปลี่ยน Journal Asset Journal เป็น Asset Journal (no budget)

change Asset Journal => Asset Journal (No-Budget)

---

pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

เมนู Accouting > Reporting> Legal Reports > Accouting Report > General Ledger
1. เวลาเลือกเงื่อนไข Date
ยอดตรง Cumlated Balance on account ให้ยอด sum ที่เป็นยอดเงิน อยู่ที่ช่อง AF และ AG
2. เวลาเลือก Period
ยอดตรงบรรทัดที่ 8 ยอดเงินยกยอด ช่อง q ,r,s ให้ย้ายตรงกับรายละเอียด ช่อง AF,AG,AH
และช่องยอดรวมของ GL ช่อง AE,AF ย้ายให้ตรงกับรายละเอียด AF,AG

#3457 move display column credit and debit

---

pabi_utils/wizard/export_xlsx_template.py
pabi_utils/wizard/export_xlsx_template_wizard.xml

Test run job
File : /pb2_addons/pabi_utils
Module : pabi_utils

#3492 - test run job

---

payment_export_text/wizard/export_parser.py

แก้ไขลำดับการรวม text ไฟล์
File : /pb2_addons/payment_export_text
Module : payment_export_text

#3509 - edit append text

---

pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

insert search_key in purchase_oeder_th jasper
File : /pb2_addons/pabi_forms/jrxml_reports/procurement

#3467 - insert search_key in purchase_oeder_th jasper

---

l10n_th_amount_text/all_docs.py

#3489 - insert currency units
File : /pb2_addons/l10n_th_amount_text
Module : l10n_th_amount_text

#3489 - insert currency units

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account/models/account_move.py
pabi_account/wizard/account_move_reverse.py
pabi_account_move_adjustment/models/account.py

FI : Reverse รายการ Internal Charge ไม่ขึ้น error "No direct reverse allowed for non adjustment doctype!
You should make reverse on source document" และ reverse ได้

#3393 allow Expense: Internal Charge,Revenue: Internal Charge

---

pabi_partner_dunning_report/report/layouts.xml

pb2_addons/pabi_partner_dunning_report/report
Date Letter

Date Letter

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account_move_adjustment/models/account.py

Bug reverse เมื่อพยายามบันทึก move_id ใน invoice

Bug reverse

---

pabi_forms/qweb_reports/account/layouts.xml

edit qweb layout.xml
File : /pb2_addons/pabi_forms/qweb_reports/account

#3523 edit work acceptance report

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account/models/account_move.py
pabi_account_move_adjustment/models/account.py

#3393 แก้บัค analytic เมื่อ move_id doctype == 'Expenses'

bug move_id not in Expenses

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account/models/account_move.py
pabi_account_move_adjustment/models/account.py
pabi_utils/wizard/export_xlsx_template.py

Bug move_id

---

pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

Update Purchase Order TH jasper
File : /pb2_addons/pabi_forms/jrxml_reports/procurement

#3480 - Update Purchase Order TH jasper

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account_move_adjustment/models/account.py

Solve Error Reverse
File : /pb2_addons/account_budget_activity, /pb2_addons/pabi_account, /pb2_addons/pabi_account_move_adjustment
Modules : account_budget_activity, pabi_account, pabi_account_move_adjustment

#3393 - Solve Error Reverse

---

account_model_purchase_invoice_plan/models/account.py
account_subscription_enhanced/models/account.py
account_subscription_enhanced/views/account_view.xml

edit Create Entries Invoice Plans
Files : /pb2_addons/account_model_purchase_invoice_plan, /pb2_addons/account_subscription_enhanced
Modules : account_model_purchase_invoice_plan, account_subscription_enhanced

#3339 - edit Create Entries Invoice Plans

---

pabi_partner_dunning_report/report/layouts.xml

แก้ไขตำแหน่ง อัพใหม่ layout date letter

layout date letter

---

payment_export_text/wizard/export_parser.py

ตาราง Invoice Details Configurations Disabled ไว้
แต่มีการถึงค่าในตารางไป ทำให้อ่านค่าว่าง เกิด Error There is nothing to validate อัพใหม่

payment export

---

pabi_procurement_report/reports/xlsx_report_pabi_purchase_tracking.py

branch: #3149-edit-purchase_tracking_report
Module: pabi_procurement_report
issue: https://mobileapp.nstda.or.th/redmine/issues/3149

#3149-edit-purchase_tracking_report

---

account_budget_activity/models/analytic.py
pabi_account/models/__init__.py
pabi_account/models/account_move.py
pabi_account_move_adjustment/models/account.py

เมื่อ Reverse แล้วทำการ post จะทำการเช็ค doctype 'adjustment' และ tax_branch ที่ไม่ใช่ doctype 'adjustment' จะ error เมื่อเป็นค่าว่าง

เช็ค doctype 'adjustment' และ tax_branch ที่ไม่ใช่ doctype 'adjustment'

---

payment_export_text/wizard/export_parser.py

Module : payment_export
FI : เช็คว่า Payment export ทำไมถึง post ไม่ได้
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3564

Branch : #3564_Payment_export_new

---

pabi_account_report/xlsx_template/templates.xml

FI : เปลี่ยนสูตรใน Template ของ Advance Payment
issue: https://mobileapp.nstda.or.th/redmine/issues/3603

#3603Advance_Payment_Report2

---

pabi_asset_management/models/account_move.py
pabi_asset_management/models/asset_removal.py
pabi_asset_management/views/asset_removal_view.xml

- เมนู Asset > Asset Action > Remova
เลือก Asset Status ส่งมอบ ให้แสดง Field Deliver to และ Delivery Date ให้ระบุ เป็นชนิด requested

Asset Removal

---

pabi_account_report/xlsx_template/templates.xml

FI : เปลี่ยนสูตรใน Template ของ Advance Payment
issue: https://mobileapp.nstda.or.th/redmine/issues/3603

#3603Advance_Payment_Report3

---

pabi_asset_management/models/account_move.py

#3437_AssetRemoval3

---

pabi_budget_monitor/models/account_budget.py
pabi_invest_construction/models/invest_construction.py
pabi_my_project/models/res_project.py

Module: pabi_invest_construction,pabi_my_project,pabi_budget_monitor
ตวจสอบ Release ของ Investment Asset, Project และ Project-C
https://mobileapp.nstda.or.th/redmine/issues/3588
https://mobileapp.nstda.or.th/redmine/issues/3544
https://mobileapp.nstda.or.th/redmine/issues/3550

#ReleaseData

---

pabi_my_project/models/res_project.py

https://mobileapp.nstda.or.th/redmine/issues/3544
Module: pabi_my_project
แก้ไขเงื่อนไข Release Project ให้ตรวจสอบเฉพาะ budget_method = 'expense'

#3544-ReleaseProject2

---

pabi_forms/qweb_reports/account/layouts.xml

#3523-edit-work_acceptance_report2

---

pabi_partner_dunning_report/report/layouts.xml

Module : pabi_partner_dunning_report
FI : แก้จดหมายทวงหนี้ครั้งที่ 3 (ตำแหน่งวันที่, อว6001 จาก / เป็น
อว6001)
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3660

Branch : #3660_Dunning_Letters_3

---

pabi_account_report/__openerp__.py
pabi_account_report/reports/xlsx_report_preprint_receipt.py
pabi_account_report/reports/xlsx_report_preprint_receipt.xml

FI : อัพใหม่ครับ ปรับปรุงรายการทะเบียนควบคุมใบเสร็จรับเงิน (Preprint
Receipt)
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3618

#3618_Preprint_Receipt_New

---

pabi_forms/__openerp__.py
pabi_forms/data/account_data.xml
pabi_forms/print_journal_entries/print_voucher_wizard.py
pabi_forms/qweb_reports/account/delivery_order_voucher.xml
pabi_forms/qweb_reports/account/employee_expense_voucher.xml
pabi_forms/qweb_reports/account/incoming_shipment_voucher.xml
pabi_forms/qweb_reports/account/internal_transfer_voucher.xml
pabi_forms/qweb_reports/account/layouts.xml

FI : Journal Entries ให้สามารถพิมพ์ Voucher ประเภทเอกสาร JIE JIR STJ ได้
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3631

Branch : #3631_Journal_Entries

---

pabi_account_report/reports/xlsx_report_sla_receipt.py
pabi_account_report/security/ir.model.access.csv

FI : เพิ่ม Authorize Model account.move.preprint
Issues : https://mobileapp.nstda.or.th/redmine/issues/3714

#3714_Authorize_Model

---

pabi_account_report/reports/xlsx_report_sla_supplier.py

FI : จะทำตัวเลือก เป็น purchase + nothing โดย เป็นตัวเลือกที่ default
Issues : https://mobileapp.nstda.or.th/redmine/issues/3679

#3679_SLA_Supplier

---

pabi_account_report/security/ir.model.access.csv

Issues : เพิ่ม default ให้ run background เพิ่มสิทธิ์ model_pabi_process
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3710

#3710_xlsx_report_sla_receipt

---

pabi_interface/models/interface_account.py

module pabi_interface restart & Update This Only
เพราะมีการสร้าง table ใหม่ด้วย

3706 fix bug existing interface

---

pabi_partner_dunning_report/report/layouts.xml

Module :pabi_partner_dunning_report
FI : เลื่อนตำแหน่ง ขอแสดงความนับถือ
Issues :https://mobileapp.nstda.or.th/redmine/issues/3730

Branch : #3730_Customer_dunning_letter_TH1

---

pabi_budget_yearend_process/models/budget_carry_over.py
pabi_budget_yearend_process/views/budget_carry_over_view.xml

module : pabi_budget_yearend_process
comment : เพิ่ม Feature Run Backgroud ในหน้าจอ Commitment Carry Over
แก้ไข ปุ่ม Save 
link issue : https://mobileapp.nstda.or.th/redmine/issues/3517

#3517_Run_Backgroud_Carry_Over_End

---

pabi_account_report/reports/xlsx_report_sla_employee.py
pabi_account_report/reports/xlsx_report_sla_employee.xml

Module :pabi_account_report
FI : เพิ่มข้อมูล Supplier-ภาครัฐ + Supplier-ภาคเอกชน
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3636

Branch : #3636_Supplier_Category

---

pabi_utils/security/ir.model.access.csv

Module : pabi_utils
FI : เพิ่มสิทธิ์ของ pabi_process
Issues : https://mobileapp.nstda.or.th/redmine/issues/3710

#3710_pabi_process_utils

---

pabi_account_report/reports/xlsx_report_output_tax.py

module : pabi_account_report
FI : Output Tax Report ให้ออกยอดรวมของใบเสร็จ
Issues : https://mobileapp.nstda.or.th/redmine/issues/3734

#3734_Output_Tax_Report

---

pabi_account_report/data/menu.xml
pabi_account_report/reports/jasper_report_cd_receivable_follow_up.xml
pabi_account_report/reports/jasper_report_cd_receivable_payment_history.xml
pabi_account_report/reports/qweb_report_receivable_confirmation_letter.xml
pabi_account_report/reports/xlsx_report_cd_receivable_balance_sheet_detail.xml
pabi_account_report/reports/xlsx_report_cd_receivable_balance_sheet_summary.xml
pabi_account_report/reports/xlsx_report_cd_receivable_confirmation.xml
pabi_account_report/reports/xlsx_report_cd_receivable_planning.xml
pabi_account_report/reports/xlsx_report_output_tax.xml
pabi_account_report/reports/xlsx_report_preprint_receipt.xml
pabi_account_report/reports/xlsx_report_receivable_before_due.xml
pabi_account_report/reports/xlsx_report_receivable_detail.xml
pabi_account_report/reports/xlsx_report_registrar_of_guarantee.xml
pabi_account_report/reports/xlsx_report_sla_receipt.xml
pabi_account_report/reports/xlsx_report_tax_exemption_receipt.xml
pabi_apps_config/security/security_group.xml
pabi_apps_config/views/pabi_menu_config.xml
pabi_loan_receivable/security/ir.model.access.csv

module : pabi_apps_config,pabi_account_report,pabi_loan_receivable
FI : ขอสิทธิ์ดูรายงานลูกหนี้ CD ให้กับ user
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/3621

#3621_Reports_CD_Receivable

---

pabi_asset_management/models/account_move.py
pabi_asset_management/models/asset.py
pabi_asset_management/models/asset_removal.py
pabi_asset_management/views/asset_removal_view.xml

#3437 asset removal 2208

---

pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml

module : pabi_froms
FI : แก้ไขใบเสร็จรับคืนเงินยืม
Issues : https://mobileapp.nstda.or.th/redmine/issues/3684

#3684_Customer_Payment

---

pabi_asset_management/models/asset_removal.py

3437-AssetRemovalRole

---

pabi_account_report/security/ir.model.access.csv

FI : รายงานภาษีขาย ติด error เรื่องสิทธิ์
Issues : https://mobileapp.nstda.or.th/redmine/issues/3781

#3781_output_tax

---

pabi_budget_yearend_process/models/budget_carry_over.py
pabi_budget_yearend_process/views/budget_carry_over_view.xml

Module: pabi_budget_yearend_process
https://mobileapp.nstda.or.th/redmine/issues/3731
ตรวจสอบการ Carry Forward Expense และเพิ่มเงื่อนไขกันดึงข้อมูลตาม Org

#3731-CarryForwardExpense

---

pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml

module : pabi_forms
FI : แก้ไขใบเสร็จรับคืนเงินยืม

#3684_Customer_Payment_New_01

---

pabi_asset_management/views/asset_removal_view.xml

#3437-AssetRemoval-0209

---

pabi_forms/jrxml_reports/account/customer_receipt_voucher.jrxml
pabi_forms/models/account_voucher.py

module : pabi_froms
FI : แก้ไขใบเสร็จรับคืนเงินยืม
Issues : https://mobileapp.nstda.or.th/redmine/issues/3684

#3684_Customer_Payment_New_02

---

pabi_asset_management/models/asset_removal.py
pabi_asset_management/views/asset_removal_view.xml

#3437-AssetRemoval-0309

---

account_voucher_net_payment/views/voucher_payment_receipt_view.xml

Module: account_voucher_net_payment
https://mobileapp.nstda.or.th/redmine/issues/3801
*แก้ไข domain menu Supplier Payments

#3801-SupplierPaymentsDomain

---

pabi_asset_management/models/asset_adjust.py
pabi_asset_management/models/asset_removal.py
pabi_asset_management/views/asset_removal_view.xml

แก้ไข validate Adjust error
แสดง fields queue_job ใน asset_removal

#UpdateAnalyticErrorDates

---

pabi_pos/models/__init__.py
pabi_pos/models/account_voucher.py
pabi_pos/models/stock.py

แก้ไข  transfer stock ให้แก้ไขโปรแกรมให้ติดลบได้ & ตอนทำตั้งหนี้
เสร็จให้โปรแกรม transfer stock auto ให้

#3529-POSCutStock

---

pabi_pos/models/__init__.py

แก้ไข  transfer stock ให้แก้ไขโปรแกรมให้ติดลบได้ & ตอนทำตั้งหนี้
เสร็จให้โปรแกรม transfer stock auto ให้

#3529-POSStock

---

pabi_pos/models/__init__.py
pabi_pos/models/account_voucher.py
pabi_pos/models/stock.py

#3529-POSTransferStock
แก้ไข  transfer stock ให้แก้ไขโปรแกรมให้ติดลบได้ & ตอนทำตั้งหนี้
เสร็จให้โปรแกรม transfer stock auto ให้

#3529-POSTransferStock

---

pabi_pos/models/__init__.py
pabi_pos/models/account_voucher.py
pabi_pos/models/stock.py

แก้ไข  transfer stock ให้แก้ไขโปรแกรมให้ติดลบได้ & ตอนทำตั้งหนี้
เสร็จให้โปรแกรม transfer stock auto ให้

#3529-POSTransferStock_

---

pabi_account/wizard/account_fiscalyear_close.py

module : pabi_account
FI: ปิดปีของระบบการเงิน แล้ว Error เพิ่ม import osv
Issues : https://mobileapp.nstda.or.th/redmine/issues/3826

#3826_period_osv

---

pabi_account_move_validator/models/account.py

**Deployment:** restart only (no update required)
ใช้ SQL ในการหา debit credit แทนการใช้ mapped function.
ปัญหาตอนแรกเกิดเนื่องจากการใช้ mapped function กับรายการจำนวนมากทำให้มีการ rounding แล้วทำให้ debit != credit เพราะมีส่วนทศนิยมปัดแล้วผิด

[FIX][#3830] FI : ปิดปีของระบบการเงิน แล้ว Error

---

account_budget_activity/models/account_budget.py
l10n_th_account/models/account.py

https://mobileapp.nstda.or.th/redmine/issues/3842
**Deployment Step:**
* Pull pb2_addons -- account_budget_activity, l10n_th_account
* Restart only
**Problem:**
Budget Control ตอนนี้ถ้าอยู๋ที่เดือน 12 (September), ทุก Period แก้ไขได้หมด ซึ่งไม่ควรแก้ได้เพราะหลักคือให้แก้ได้เฉพาะ Future Period
** แต่ต้องการให้เพิ่มเติมด้วยคือ ให้แก้เดือนปัจจุบันได้ด้วย
**Solution**
ปัญหาเกิดจากการคำนวนผิดพลาดที่ get_num_period_by_period() ซึ่งถ้าเดือน 12 mod 12 ปกติได้ 0 ต้องปรับให้เป็น 11 (เพื่อให้เดือนปัจจุบันแก้ได้ด้วย)

3842 - BG: ขอให้ตรวจสอบ Budget Control ของ Unit-based และ Personnel

---

pabi_budget_internal_charge/models/hr_expense.py
pabi_budget_internal_charge/security/security_rule.xml

เพิ่ม field pay_to ใน module hr.expense.line เพื่อลดการ join database table hr.expense.expense

#3834_fix_performance_internal_charge

---

pabi_purchase_work_acceptance/models/purchase.py
pabi_purchase_work_acceptance/views/purchase_view.xml

module : pabi_purchase_work_acceptance
PO : Add PO Item ให้ copy รายละเอียดทั้งหมดมาให้
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/3466

#3466_Add_PO_Item

---

pabi_asset_management/models/account_move.py

(ไม่ต้องกด update module)
Module: pabi_asset_management 
https://mobileapp.nstda.or.th/redmine/issues/3847
แก้ไขการดึง Section /Project/ครุภัณฑ์หลัก/โครงสร้าง

#3847-AssetRemoval

---

pabi_account/wizard/__init__.py
pabi_account/wizard/account_open_closed_fiscalyear.py

แก้ไข performance การลบข้อมูลใน database ที่เป็นสาเหตุ Run เมนู Cancel Close Fiscal Year แล้ว offline
โดยการปิดการ Trigger ใน database เพื่อให้ระบบทำงานเร็วขึ้น

3835_performance_cancel_close_fiscalyear

---

pabi_pos/models/__init__.py
pabi_pos/models/account_voucher.py

**Restart Only
แก้ไข  ตอนทำตั้งหนี้เสร็จให้โปรแกรม transfer stock auto

#3529-PosStock_1309

---

pabi_budget_yearend_process/models/project_balance_carry_forward.py
pabi_budget_yearend_process/views/project_balance_carry_forward_view.xml
pabi_my_project/models/res_project.py

#3838 ปรับปรุงระบบในการยกยอดงบประมาณสิ้นปี

---

account_budget_activity/models/analytic.py
account_budget_activity/views/hr_expense_view.xml
account_budget_activity/views/purchase_request_view.xml
account_budget_activity/views/purchase_view.xml
account_budget_activity/views/sale_view.xml
pabi_budget_yearend_process/models/budget_carry_over.py

แก้ไขหน้า PR, PO, EX, SO ให้แสดง field Budget Fiscal Year

#3857 budgeting commitment

---

pabi_account_report/reports/xlsx_report_pnd1.py
pabi_account_report/reports/xlsx_report_pnd1.xml

Module: pabi_account_report
https://mobileapp.nstda.or.th/redmine/issues/3868#change-13684
แก้ไข filter fields Calendar Period

#3868-PND1

---

pabi_my_project/models/project_web_interface.py

ลบ function การเรียกใช้งาน _release_fiscal_budget ให้ไม่ต้อง update release

#3872 not update release budget from service

---

account_trial_balance_report/models/trial_balance_report.py

Module: account_trial_balance_report
https://mobileapp.nstda.or.th/redmine/issues/3866
แก้ไข รายงาน Trial Balance (WEB)ให้ แสดงเฉพาะ account ที่เลือก และ
แก้ไขจำนวนเงิน

#3866-TrialBalance

---

l10n_th_account_pnd_form/report/report_pnd_form.py

module : l10n_th_account_pnd_form
FI : รายงานภาษี ภงด. 3 ไม่ขึ้น
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/3869

#3869_Thai_Tax_Reports_PND3

---

pabi_account_report/reports/asset_register_report.py

ส่งข้อมูลเปรียบเทียบรายการครุภัณฑ์  Org สก. จากรายงาน  Asset Register
Report

Asset_Register_Org1

---

pabi_my_project/models/project_web_interface.py
pabi_my_project/models/res_project.py

แก้ไขปัญหา release amount เป็น 0

3872_fix_release_amount_case2

---

pabi_account_report/reports/xlsx_report_purchase_invoice_plan.py

**Restart only
Module: pabi_account_report 
แก้ไข query ของรายงาน

#InvoicePlan

---

pabi_my_project/models/res_project.py

แก้ไขเพิ่มเงื่อนไข กรณี release and plan ไม่เท่ากัน

3872_ignore budget release

---

pabi_asset_management/models/account_move.py
pabi_asset_management/models/asset_removal.py

***Restart Only
https://mobileapp.nstda.or.th/redmine/issues/3865
update move line

#3865-InternalChargeStock

---

pabi_account_report/reports/xlsx_report_sla_employee.py

FI : เพิ่มเงื่อนไขการเรียกรายงาน และเช็คการแสดงผล ฟิลด์ Accepted Date
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3888

#3888_SLA_Expense_supplier

---

pabi_account_report/reports/asset_register_report.py

module : pabi_account_report
FI : รายงานประมาณค่าเสื่อมราคา ช่อง purchase value current year
ไม่แสดงค่า
Issues : https://mobileapp.nstda.or.th/redmine/issues/3894

#3894_Asset_Register_Year

---

pabi_account_move_adjustment/__openerp__.py
pabi_account_move_adjustment/models/__init__.py
pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/models/stock.py
pabi_account_move_adjustment/models/stock_account.py
pabi_account_move_adjustment/views/account_move_priority_view.xml
pabi_account_move_adjustment/views/stock_view.xml

Deployment : Restart and Update module 'pabi_account_move_adjustment'

#3899 [FIX] link account_move and stock_move

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/wizard/account_move_reverse_view.xml

module : pabi_account_move_adjustment
FI : Import Journal Entry ให้เพิ่มปุ๋ม ให้ post Journal ได้หลายๆ doc
Issues : https://mobileapp.nstda.or.th/redmine/issues/3790

#3790_Import_Post_Entries_2

---

pabi_budget_yearend_process/models/project_balance_carry_forward.py
pabi_budget_yearend_process/views/project_balance_carry_forward_view.xml

- เพิ่ม field filter Program ในหน้า Project Balance C/F
- เพิ่ม flag ให้เลือกเมื่อต้องการให้ released amount = consumed amount และบันทึกเก็บใน history
Deployment : Restart and update module 'pabi_budget_yearend_process'

#3940 fix carry forward released amount equal consumed amount

---

pabi_account_move_adjustment/models/account.py
pabi_pos/__openerp__.py
pabi_pos/data/data.xml
pabi_pos/models/account_voucher.py
pabi_pos/models/pos_web_interface.py
pabi_pos/models/sale.py
pabi_pos/views/sale_view.xml

Module: pabi_pos,pabi_account_move_adjustment
https://mobileapp.nstda.or.th/redmine/issues/3921
เพิ่ม Method interface POS cancel
เพิ่ท Sequence เลขที่ใบเสร็จของ POS 
แก้ไข Transfer Stock จังหวะ validate payments ให้ Transfer on background
แก้ไข Reference Journal Entries

#3921-POS_interface

---

pabi_procurement_report/reports/xlsx_report_pabi_stock_balance.py
pabi_procurement_report/reports/xlsx_report_pabi_stock_balance.xml

module : pabi_procurement_report
PO : รายงาน Stock Balance เพิ่มเงื่อนไข category
Issues : https://mobileapp.nstda.or.th/redmine/issues/3901

#3901_Stock_Balance

---

l10n_th_account/models/account_voucher.py

ปัญหาเกิดจากระบบส่งการคำนวณที่มีทศนิยมหลายตำแหน่ง
จึงแก้ไขด้วยการ round() ทศนิยม 2 ตำแหน่ง
Deployment : Restart Only

#3946 [FIX] rounding currency tax thailand

---

account_budget_activity/models/account_move_line.py
account_budget_activity/models/analytic.py
pabi_asset_management/models/asset_removal.py

**Restart Only
Module: account_budget_activity,pabi_asset_management
https://mobileapp.nstda.or.th/redmine/issues/3875
-แก้ไข Transfer Removal error cost center เก่า
-เวลาเลือก asset status ส่งมอบ default Removal Entry Policy "Residual Value"

#3875-TransferRemovalError_2

---

pabi_utils/wizard/export_xlsx_template.py

Module: pabi_utils (Restart Only)
แก้ไข Special Character

#SpecialCharacters

---

pabi_account_report/reports/xlsx_report_purchase_invoice_plan.py
pabi_account_report/reports/xlsx_report_purchase_no_invoice_plan.py

module: pabi_account_report (Restart Only)
แก้ไย filter budget error

#InvoicePlanReport

---

stock_request/models/stock_request.py

Module : stock_request
Stock : ปรับฟิลด์ Receiver ให้เป็น Require Field ก่อนกดปุ่ม Request
Issues : https://mobileapp.nstda.or.th/redmine/issues/3922

#3922_My_Stock_Request

---

pabi_purchase_work_acceptance/views/purchase_view.xml

Module : pabi_purchase_work_acceptance
PO : ปรับแก้ไขให้ Activity Group และ Activity Rpt ใน Line Item ของแท็บ
Product หน้า PO ให้เป็น Require field
Issues : https://mobileapp.nstda.or.th/redmine/issues/3951

#3951_Require_field_Activity_Group_And_Activity_Rpt

---

pabi_forms/jrxml_reports/account/receipt_supplier_form.jrxml
pabi_forms/models/account_voucher.py

FI : ขอเพิ่ม Text ข้อความจำนวนเงินเป็นตัวอักษร ในใบรับเงิน
Issues : https://mobileapp.nstda.or.th/redmine/issues/3977

#3977_Text_total_Supplier_payment

---

pabi_forms/models/account_voucher.py

FI : ขอเพิ่ม Text ข้อความจำนวนเงินเป็นตัวอักษร ในใบรับเงิน
Issues : https://mobileapp.nstda.or.th/redmine/issues/3977

#3977_Text_wa_total_Supplier_payment

---

pabi_account_financial_report_webkit/report/common_reports.py
pabi_account_financial_report_webkit_xls/report/general_ledger_xls.py

module:pabi_account_financial_report_webkit,pabi_account_financial_report_webkit_xls
FI : ช่วยเช็คให้ด้วยค่ะ ว่ารายงาน GL Field Post by แสดงถูกต้องหรือไม่
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/3987

#3987_GL_Field_Post_by

---

pabi_my_project/models/project_web_interface.py
pabi_my_project/models/res_project.py

แก้ไขไม่ให้ระบบ update released เมื่อมาจาก function update_project
โดยการเพิ่ม context not_update_released=True

#3872 [FIX] not update released amount from web service

---

pabi_account_financial_report_webkit/report/common_reports.py

module:pabi_account_financial_report_webkit
FI : ช่วยเช็คให้ด้วยค่ะ ว่ารายงาน GL Field Post by แสดงถูกต้องหรือไม่
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/3987

#3987_GL_Field_Post_by_Edit

---

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py

เพิ่มเงื่อนไขจะ update ถ้า state invoice == draft เท่านั้น

[FIX] #3968 add condition update when state invoice = draft only

---

pabi_user_profile/models/hr_employee.py
pabi_user_profile/views/hr_employee_view.xml

module : pabi_user_profile
[PABI2 Report] เพิ่ม fields สำหรับกำหนดสิทธิ์เรียกดูรายงานของ พนง.
ตามเงื่อนไขของ Org
ISSUES : https://mobileapp.nstda.or.th/redmine/issues/4005

#4005_Add_Fields_Define_Access

---

hr_expense_advance_clearing/models/hr_expense.py

แก้ไขให้ปุ่ม AV Outstanding filter เลือกเอกสารที่ไม่ใช่ Rejected
Deployment : Restart Only

#3947 [FIX] filter AV Clearing state not in rejected

---

hr_salary/models/hr_salary.py

แก้ไขให้ระบบสร้าง date move จากวันที่ปัจจุบันแทน date ใน salary

#4009 create date today in move

---

pabi_budget_plan_monitor/models/budget_plan_project.py
pabi_my_project/models/res_project.py

แก้ไขการแสดงค่าให้ถูกต้องเมื่อ generate budget plan project

#3980 [FIX] Generate Budget Plan project

---

pabi_my_project/models/res_project.py
pabi_my_project/views/res_project_view.xml

Module : pabi_my_project
Report : เพิ่ม field
เพื่อกำหนดสิทธิ์ในการเรียกดูรายงานสำหรับมาชิกโครงการ
Issues : https://mobileapp.nstda.or.th/redmine/issues/4026

#4026_Add_field_report_check

---

pabi_pos/models/pos_web_interface.py

update interface product send barcode

#WebInterfaceProduct

---

hr_expense_advance_clearing/models/hr_expense.py

แก้ไขการ query advance clearing ให้ระบบดึงข้อมูลของ CN มาแสดงในระบบด้วย

#3937 add CN in advance clearing

---

pabi_account_report/__openerp__.py
pabi_account_report/reports/__init__.py
pabi_account_report/reports/asset_register_report.py
pabi_account_report/reports/xlsx_report_purchase_invoice_plan.py
pabi_account_report/reports/xlsx_report_purchase_no_invoice_plan.xml
pabi_procurement_report/__openerp__.py
pabi_procurement_report/wizards/pabi_purchase_billing_report.xml
pabi_procurement_report/wizards/pabi_purchase_invoice_plan_report.xml

Module: pabi_account_report,pabi_procurement_report (Restart & Update This Only)
https://mobileapp.nstda.or.th/redmine/issues/4018
- รวมรางาน Purchase Invoice Plan และ Purchase No Invoice Plan
- เพิ่มรายงาน Purchase Billing และ Purchase Invoice Plan ในเมนู Purchase Report
https://mobileapp.nstda.or.th/redmine/issues/4032
- แก้ไข Query และ Filter ใน รายงาน Asset Register

#4018-PurchaseReport

---

pabi_forms/jrxml_reports/account/receipt_supplier_form.jrxml
pabi_forms/models/account_voucher.py

module : pabi_forms
FI : จำนวนเงินตัวอักษรไม่มีค่า ออกเป็น ศูนย์บาทถ้วน
Issues : https://mobileapp.nstda.or.th/redmine/issues/4029

#4029_FIX_Total_Text_Zero

---

pabi_forms/jrxml_reports/procurement/work_acceptance2.jrxml

PO : การแสดงผลค่าปรับแบบระบุเองของ Total Fine ใน WA
Issues : https://mobileapp.nstda.or.th/redmine/issues/4034

#4034_Total_Fine_WA

---

pabi_account/models/account_move_line_v7.py

check context ถ้ามาจาก clear prepaid ไม่ต้องตรวจสอบ journal

#4035 [FIX] clear prepaid date

---

pabi_forms/qweb_reports/account/layouts.xml

FI : voucher TP ลงวันที่ใต้ Account by ผิดค่ะ
Issues : https://mobileapp.nstda.or.th/redmine/issues/4039

#4039_voucher_TP_Account_by

---

pabi_import_journal_entries/models/pabi_import_journal_entries.py
pabi_import_journal_entries/views/pabi_import_journal_entries_view.xml

ทดสอบแก้ไขโดยการใช้ commit เพื่อให้ระบบแบ่งการทำงาน

[FIX] job error by commit every 100 record

---

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py

Module : pabi_purchase_work_acceptance
PO : ปรับแก้ไขยอด amount_tax ของ purchase_work_acceptance
ให้ตรงกับยอดของ purchase_order
Issues : https://mobileapp.nstda.or.th/redmine/issues/4059

#4059_Amount_Tax_WA

---

pabi_purchase_work_acceptance/models/account_invoice.py
pabi_purchase_work_acceptance/models/purchase_work_acceptance.py

Module: pabi_purchase_work_acceptance (Restart Only)
*ปรับปรุงค่า total_fine_cal ใน WA ให้เท่ากับ total_fine เมื่อมีการแก้ไข
total_fine 
*แก้ไข Unit Price และ Amount ใน invoice_line ที่อ้างอิง WA
โดยให้ยอดตรงกับค่า Total Fine ใน WA
https://mobileapp.nstda.or.th/redmine/issues/4058

#4058-WA_Invoiceline

---

pabi_forms/qweb_reports/account/layouts.xml

Module: pabi_forms
*แก้ไข layout report
https://mobileapp.nstda.or.th/redmine/issues/4076

#4076-DoctypeSLPrintvoucher

---

pabi_forms/qweb_reports/account/layouts.xml

Module: pabi_forms
FI: voucher หน้า KV ขึ้นชื่อซ้ำ
Issues : https://mobileapp.nstda.or.th/redmine/issues/4079

#4079_Voucher_KV_Duplicate_Name

---

res_partner_ext/models/partner.py
res_partner_ext/views/partner_view.xml

Module : res_partner_ext
FI : เพิ่ม filed Email Accountant ใน master customer, supplier
Issues : https://mobileapp.nstda.or.th/redmine/issues/4080

#4080_Email_Accountant

---

pabi_asset_management/models/account_move.py

Module: pabi_asset_management (Restart Only)
*Update Detail move_line ของ doc ที่มี journal เป็น STJ, TP
https://mobileapp.nstda.or.th/redmine/issues/3597
https://mobileapp.nstda.or.th/redmine/issues/4055

#MoveLineDetail

---

l10n_th_account_tax_detail/models/account_tax_detail.py

module:l10n_th_account_tax_detail
FI : ให้เช็คความสัมพันธ์ของการบันทึก Taxs กับ Income tax form
Issues:https://mobileapp.nstda.or.th/redmine/issues/4021

#4021_check_tax_and_income_tax_form

---

pabi_asset_management/views/asset_view.xml

module:pabi_asset_management
FI: เพิ่ม filter และ Group by
Issues:https://mobileapp.nstda.or.th/redmine/issues/4092

#4092_filter_group_by

---

l10n_th_account_tax_detail/models/account_invoice.py
l10n_th_account_tax_detail/models/account_tax_detail.py

module:l10n_th_account_tax_detail
FI : ให้เช็คความสัมพันธ์ของการบันทึก Taxs กับ Income tax form
Issues:https://mobileapp.nstda.or.th/redmine/issues/4021

#4021_fix_check_tax_and_income_tax

---

pabi_asset_management/models/asset_removal.py
pabi_asset_management/wizard/account_asset_remove.py

แก้ไข function remove ให้ active = False

#4078 [FIX] stamp active false when remove

---

pabi_pos/models/pos_web_interface.py

*แก้ไข query สำหรับ interface product ให้ดึงเฉพาะ active product

#4100 [POS] InterfaceProduct

---

payment_export_text/wizard/export_parser.py

Module: payment_export_text (Restart Only)
*แก้ไข encoding ไฟล์

#4103 EncodingPaymentExportFile

---

pabi_forms/jrxml_reports/account/receipt_supplier_form.jrxml

module : pabi_forms
FI : ใบเสร็จรับเงินไม่แสดงเศษสตางค์
Issues : https://mobileapp.nstda.or.th/redmine/issues/4101

#4101_Add_Amount_Text_TH

---

l10n_th_account_tax_detail/models/account_tax_detail.py

Module : l10n_th_account_tax_detail
FI : FI : ให้เช็คความสัมพันธ์ของการบันทึก Taxs กับ Income tax form (2)
Issue : https://mobileapp.nstda.or.th/redmine/issues/4110

#4110_check_income_tax_form_2

---

pabi_my_project/models/res_project.py

แก้ไขการลง released amount ผิด
เพิ่มการ check เงื่อนไขเฉพาะ budget_method = 'expense'

#3872 [FIX] released to expense only

---

pabi_account_report/reports/asset_register_report.py

Module: pabi_account_report (Restart & Update Module)
**Update filter report wizard
https://mobileapp.nstda.or.th/redmine/issues/4105

#4105-AssetRegisterReport

---

l10n_th_account/models/account_invoice.py

Module: l10n_th_account (Restart Only)
เพิ่ม เงื่อนไขการเช็ค document customer invoice ไม่ต้องเช็คเงื่อนไข
Due Date is greater than or equal to Posting date
https://mobileapp.nstda.or.th/redmine/issues/4114#change-14523

#4114-ConstrainsInvoice

---

pabi_base/models/res_investment_structure.py
pabi_base/views/res_investment_structure_view.xml

Module : pabi_base
BG: หน้าจอ Investment Asset (set ค่า Section และ Org ตาม Requester)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4112

#4112_set_Section_and_Org_base_on_Requester

---

pabi_purchase_billing/models/account_invoice.py

Module : pabi_purchase_billing
PO : Ascending Sort Installment of Supplier Invoice
Issues : https://mobileapp.nstda.or.th/redmine/issues/4113

#4113 ascending sort installment of supplier invoice

---

pabi_account_report/reports/xlsx_report_receivable_detail.py
pabi_account_report/reports/xlsx_report_receivable_detail.xml

FI:แก้ไขเงื่อนไขรายงาน Receivable Detail filter Document
Issues : https://mobileapp.nstda.or.th/redmine/issues/4121

#4121_filter_Document

---

pabi_my_project/models/res_project.py

- แก้ไขการตรวจสอบ ในแต่ละปี
ถ้าบรรทัดสุดท้ายของปีนั้นมี released เหลือ
ให้ใส่ค่า released ทั้งหมดลงไป
- แก้ไขการ released ให้ check เฉพาะ budget_method = expense only

#3872 [FIX] budget released last line = plan amount

---

pabi_budget_monitor/models/purchase.py
pabi_budget_monitor/models/purchase_request.py

แก้ไขการ check budget ของ PR, PO
โดยเปลี่ยนจาก check วันที่หน้า doc
เป็น วันที่กด ณ ปัจจุบัน

#4099 [FIX] change date pr, po check budget to date today

---

pabi_asset_management/data/asset_status.xml
pabi_asset_management/models/asset.py
pabi_asset_management/models/asset_transfer.py

- แก้ไขการ transfer asset ให้เปลี่ยน state = removed, stamp date remove and active = False
- บันทึก date_document ในหน้า AN ให้เป็นวันปัจจุบัน

#4119 [FIX] transfer asset

---

account_budget_activity/report/budget_monitor_dimension.py

Module: account_budget_activity
BG: ปรับปรุงข้อมูลใน Tab Budget Monitor ส่วน Revenue
Issues: https://mobileapp.nstda.or.th/redmine/issues/4131

#4131_edit_Revenue_in_Budget_Monitor

---

l10n_th_account_pnd_form/report/report_pnd1a_form.jrxml
l10n_th_account_pnd_form/wizard/print_pnd_form_wizard.py

module:l10n_th_account_pnd_form
FI : แก้ไข pdf ภงด.1ก
Issues:https://mobileapp.nstda.or.th/redmine/issues/4128

#4128_edit_pdf_pnd1a

---

l10n_th_account_pnd_form/data/report_data.xml
l10n_th_account_pnd_form/report/report_pnd3a_form.jrxml
l10n_th_account_pnd_form/wizard/print_pnd_form_wizard.py
l10n_th_account_pnd_form/wizard/print_pnd_form_wizard.xml

FI : ใบแนบ ภงด.3 ก.
Issues : https://mobileapp.nstda.or.th/redmine/issues/4072

#4072_Form_PND3A

---

pabi_account/models/account.py
pabi_account/views/account_view.xml

Module : pabi_account
FI: Config Accounts > Accounts ให้เก็บ History
Issues : https://mobileapp.nstda.or.th/redmine/issues/4120

#4120_History_Accounts

---

hr_expense_advance_clearing/models/hr_expense.py

แก้ไขให้ระบบเก็บ amount to clearing  2 digits เพื่อแก้ไขปัญหาทศนิยม

#4124 [FIX] keep amount to clearing 2 digits

---

l10n_th_account_pnd_form/report/report_pnd1a_form.jrxml

module:l10n_th_account_pnd_form
FI: รายงานภาษี ภงด. 1 ยอดรวมติดลบ
issues:https://mobileapp.nstda.or.th/redmine/issues/4168

#4168_sum_pnd1a

---

pabi_account_financial_report_webkit/report/common_balance_reports.py
pabi_account_financial_report_webkit/report/templates/account_report_trial_balance.mako
pabi_account_financial_report_webkit_xls/report/trial_balance_xls.py

แก้ไขตาม https://mobileapp.nstda.or.th/redmine/issues/4142
หมวดสินทรัพย์ = ช่อง Debit -Initial_Debit
หมวดหนี้สิน,ทุน = ช่อง Credit - Initial_Credit
แก้ไขเฉพาะส่วนของ Accounting Report Trial Balance (Filter by Period & Date)
ไฟล์ Excel
ไฟล์ PDF

[FIX] #4142 - Accounting_Report_Trial_Balance

---

l10n_th_account_pnd_form/report/report_pnd1a_form.jrxml

module:l10n_th_account_pnd_form
FI: รายงานภาษี ภงด. 1 เลข Running ผิด และไม่เอายอด base ที่เป็น 0.0
issues:https://mobileapp.nstda.or.th/redmine/issues/4170

#4170_edit_pnd1a

---

l10n_th_account_pnd_form/report/report_pnd3a_form.jrxml

FI : ภงด.3 ก
Isses : https://mobileapp.nstda.or.th/redmine/issues/4169

#4169_edit_pnd_3_a

---

pabi_budget_monitor/models/res_org_structure.py
pabi_budget_monitor/models/res_other_structure.py
pabi_budget_monitor/views/res_org_structure_view.xml
pabi_budget_monitor/views/res_other_structure_view.xml

module: pabi_budget_monitor
BG: เพิ่ม Section เพื่อกำหนดสิทธิ์ใน Job order
issues: https://mobileapp.nstda.or.th/redmine/issues/4173

#4173_section_report_job

---

l10n_th_account_pnd_form/report/report_pnd3a_form.jrxml

FI : PND Form ภงด. 3ก
Issues : https://mobileapp.nstda.or.th/redmine/issues/4178

#4178_Delete_Field_partner_search_key_In_pnd3a

---

pabi_asset_management/models/stock_account.py

แก้ไข กรณีที่ทำ IN และเป็นสกุลเงินต่างประเทศ
ระบบจะคำนวณ Currency Rate จากวันที่กด Transfer

#3938 [FIX] calcurate currency in stock to today

---

pabi_base/models/product.py

module: pabi_base
FI : ขอเพิ่ม History ให้กับข้อมูล Product master
issues: https://mobileapp.nstda.or.th/redmine/issues/4175

#4175_product_message_history

---

l10n_th_account_pnd_form/report/withholding_tax_cert.jrxml

FI: รายงานภาษี ภงด. 1 ทวิ ข้อมูลขึ้นไม่ครบถ้วน
Issues: https://mobileapp.nstda.or.th/redmine/issues/4190

#4190_add_wht_income_type

---

pabi_invest_construction/__openerp__.py
pabi_invest_construction/models/invest_construction.py
pabi_invest_construction/views/invest_construction_view.xml
pabi_invest_construction/wizard/__init__.py
pabi_invest_construction/wizard/project_close_phase.py
pabi_invest_construction/wizard/project_close_phase_wizard.xml

สิ่งที่แก้ไข
1. เมื่อมีการปรับปรุง Project Manager ให้ปรับ Field Project Manager Section และ Org อัตโนมัติ
และ Set Disable Field Project Manager Section และ Org
2. หน้าจอ Phase เมื่อกรอก Duration ให้ Set Date Expansion = Start Date + Duration (months)
กรณีที่ End Date ยังไม่มีค่า ให้ Set End Date = Date Expansion
3. เพิ่ม Field Close Date
เมื่อกดปุ่ม Close ต้องให้ระบุ Close Date ก่อน
4. Generate Calendar Period ตั้งแต่ Start Date จนถึง Date Expansion
5. เมื่อมีการกดปุ่ม Delete ในหน้าจอ Phase หรือ ProjectC ให้ตรวจสอบว่ามี Comsume Amount หรือไม่ ถ้ามีให้แสดง Message “If consumed amount already have values, Cannot delete ProjectC/Phase.” และไม่ให้ทำการ Set สถานะเป็น Delete

#4117 - BG: ปรับปรุงหน้าจอ Project C

---

pabi_account_report/xlsx_template/templates.xml

FI : ช่วยตรวจสอบ คิวรี่
Issues : https://mobileapp.nstda.or.th/redmine/issues/4196

#4196_change_poc_code

---

pabi_account_report/reports/xlsx_report_sla_employee.py

Module: pabi_account_report (Restart & Update This Only)
ปรับ code และ query ของรายงาน
https://mobileapp.nstda.or.th/redmine/issues/4195

#4195-SLA_report

---

pabi_base/models/res_investment_structure.py

#4112-InvestmentAsset
Module: pabi_base (Restart & Update This Only)
เพิ่ม store=true ฟิลด์  org_id, owner_section_id
https://mobileapp.nstda.or.th/redmine/issues/4112

#4112-InvestmentAsset

---

l10n_th_account_pnd_form/report/report_pnd1a_form.jrxml

#3891_print_pnd_form_fix

---

pabi_account_report/reports/xlsx_report_sla_employee.py
pabi_account_report/reports/xlsx_report_sla_receipt.py

Module: pabi_account_report
เพิ่ม query สำหรับรายงาน SLA Receipt
https://mobileapp.nstda.or.th/redmine/issues/4198

#4198-SLA_Receipt

---

l10n_th_account_pnd_form/report/withholding_tax_cert.jrxml

#3891_fix_print_pnd_form

---

pabi_asset_management/models/asset_adjust.py

Module: pabi_asset_management (Restart Only)
*ปรับปรุง Expense to Asset ถ้าไม่มี Invoice analytic line
ให้ดึงจาก analytic line อื่น
https://mobileapp.nstda.or.th/redmine/issues/4171

#4171-AssetAdjustment

---

pabi_forms/jrxml_reports/procurement/work_acceptance2.jrxml

Module : pabi_forms (Restart & Update This Only)
แก้ไข error body null
Issues : https://mobileapp.nstda.or.th/redmine/issues/4183

#4183_Change_Form_Currency_WA2

---

pabi_validate_pricediff/models/invoice.py

แก้ไขปัญหาที่ระบบสร้าง line price diff แต่ price diff เป็น 0
สาเหตุเกิดจากการ check เงื่อนไข แล้วทศนิยมไม่ตรงกัน (ปัญหาของ python)
แก้ไขด้วยการใช้ float_compare เปรียบเทียบทศนิยม

#3948 [FIX] used float_compare instead !=

---

pabi_procurement/views/purchase_view.xml

Module : pabi_procurement
PO : Create Filter Currency View PO
Issues : https://mobileapp.nstda.or.th/redmine/issues/4182

#4182_Create_Filter_Currency_View_PO

---

hr_salary/views/hr_salary_view.xml

Module : hr_salary
FI : Salary Expense เพิ่มเติม Group by
Issues : https://mobileapp.nstda.or.th/redmine/issues/4230

#4230_Add_Group_By_In_Salary Expense

---

pabi_invest_construction/models/invest_construction.py

[FIX] Issue - ตรวจสอบหน้าจอ Project C เมื่อ Create แล้ว Error

---

pabi_account_report/reports/xlsx_report_purchase_invoice_plan.py

Module: pabi_account_report (Restart Only)
**แก้ไข error
https://mobileapp.nstda.or.th/redmine/issues/4234

#4234-PurchaseInvoiceReport

---

pabi_forms/jrxml_reports/procurement/work_acceptance2.jrxml
pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
pabi_purchase_work_acceptance/views/purchase_work_acceptance_view.xml

Module : pabi_purchase_work_acceptance , pabi_forms
PO : เพิ่มฟิลด์ Action Date ในหน้าใบตรวจรับพัสดุ (WA)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4229

#4229_Add_Field_Action_Date_WA

---

pabi_partner_dunning_report/models/pabi_partner_dunning_letter.py
pabi_partner_dunning_report/views/pabi_partner_dunning_letter_view.xml

Module : pabi_partner_dunning_report
FI : ขอเพิ่ม Field Validator ใน Dunning Letter
Issues : https://mobileapp.nstda.or.th/redmine/issues/4247

#4247_Add_Field_Validator_dunningLetter

---

l10n_th_account/models/account_wht_cert.py
l10n_th_account/views/account_wht_cert.xml

#3432 - เพิ่ม fields message_ids ใน account_wht_cert
File : /pb2_addons/l10n_th_account
Modules : l10n_th_account

#3432 - insert message_ids in account_wht_cert_New

---

l10n_th_account/models/account_wht_cert.py

Module : l10n_th_account
FI:ช่วยแก้โปรแกรมหน้า Create WHT ให้หน่อยค่ะ
Issues : https://mobileapp.nstda.or.th/redmine/issues/4257

#4257_fix_compute_date

---

pabi_account_report/reports/xlsx_report_sla_employee.py

Module: pabi_account_report (Restart Only)
แก้ไข query report error
https://mobileapp.nstda.or.th/redmine/issues/4195

#4195-SLA_Emp_Report

---

pabi_forms/jrxml_reports/procurement/purchase_order_EN.jrxml

PO : ขอเพิ่ม Terms and Conditions ในแบบฟอร์มใบสั่งซื้สั่งจ้างภาษาอังกฤษ
(Purchase Order ENG)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4231

#4231_Add_Terms_and_Conditions_PurchaseOrder_ENG

---

pabi_account_financial_report_webkit/wizard/aged_partner_balance_wizard.py
pabi_account_financial_report_webkit/wizard/aged_partner_balance_wizard.xml

module : pabi_account_financial_report_webkit
FI : ขอเพิ่ม tab Accounts filters ที่เป็นหน้าค้นหา Account code
issues : https://mobileapp.nstda.or.th/redmine/issues/3183

#3183_add_tab_accounts_filters

---

pabi_my_project/models/res_project.py
pabi_my_project/views/res_project_view.xml

Module: pabi_my_project (Restart & Update This Only)
เพิ่มฟิลด์สำหรับ release budget และแก้ไขการคำนวน release_amount
https://mobileapp.nstda.or.th/redmine/issues/4174

#4174-ProjectReleaseBudget

---

pabi_account_report/reports/xlsx_report_pv_pe.py
pabi_account_report/reports/xlsx_report_pv_pe.xml

FI : รายงาน PE PV
Issues : https://mobileapp.nstda.or.th/redmine/issues/4238

#4238_EDIT_PV_PE_Report

---

l10n_th_account/models/account_voucher.py
l10n_th_account/wizard/clear_undue_vat_wizard.py

Module: l10n_th_account (Restart Only)
*เพิ่ม detail Recognize Vat item
https://mobileapp.nstda.or.th/redmine/issues/3803

#3803-JournalDetail

---

pabi_account_report/reports/xlsx_report_gl_project.py

FI: รายงาน GL Project เรียก period 13 แต่ออก period 12 มาด้วย
Issues: https://mobileapp.nstda.or.th/redmine/issues/3898

#3898_GL_Project_period

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/views/account_view.xml

Module: pabi_account_move_adjustment (Restart&Update Module)
*เพิ่ม require field budget on account_type 
*เพิ่มตรวจสอบ require AG&A on Journal Adj.Budget
*เพิ่มตรวจสอบ require Budget on Journal Adj.No.Budget
https://mobileapp.nstda.or.th/redmine/issues/4268

#4268-JournalAdj

---

pabi_account_report/reports/xlsx_report_cgd.py

FI : รายงานกรมบัญชีกลาง(เบิกจ่าย EX) ประจำเดือน
module : pabi_account_report
issues: https://mobileapp.nstda.or.th/redmine/issues/4219

#4219_edit_kv_postingdate

---

pabi_budget_plan/models/res_invest_asset.py
pabi_budget_plan/views/invest_asset.xml

https://mobileapp.nstda.or.th/redmine/issues/4259
deployment: restart & update this only module " pabi_budget_plan "
- เพิ่ม Field Fund Type <แสดง List project_fund_type>
- เพิ่ม Tab Project โดยให้สามารถเลือก Project Master ซึ่งมีข้อมูลแสดงดังนี้ Org, Code, Name, Program, Status

4259 Add - Tab Project

---

pabi_budget_drilldown_report/models/budget_drilldown_report.py
pabi_utils/models/ws.py

- pabi_utils
- budget_drilldown_report

#4239 [FIX] performance turing Budget Drilldown

---

pabi_my_project/models/res_project.py

- แก้ไข performace การทำ released amount ซึ่งปัญหาเกิดจากการใช้ ORM นำข้อมูลทั้งหมดมาและ filtered ข้อมูลที่ไม่จำเป็นออก เปลี่ยนไปใช้การ query database direct โดยการเอาข้อมูลเท่าที่จำเป็นแทน
ผลการทดสอบ xml_P1951071.xml ตั้งแต่ข้อมูลเข้าระบบจนกระทั่งเสร็จสิ้น (เวลาคร่าวๆ)
79 s -> ORM
53 s -> Query

#4239 [FIX] performance turning my project

---

pabi_budget_plan_monitor/models/budget_plan_project.py

ปรับแก้ code โดยเปลี่ยนการทำงานจากการเรียกใช้ ORM เป็นการ query database โดยตรง
ผลการทดสอบ(เฉพาะใน function _prepare_prev_fy_lines)
45 s -> ORM
4 s -> Direct Query Database
Deployment : Restart only

#4239 [FIX] performance turning Prev.FY in budget_plan

---

pabi_budget_yearend_process/models/project_balance_carry_forward.py

- แก้ไข performance การทำ carry forward โดยเปลี่ยนจากการใช้ ORM -> query direct database
ผลการทดสอบการ carry forward / line
40 s / line
4 s / line

#4239 [FIX] performance turning carry forward

---

pabi_chartfield/models/chartfield.py
pabi_chartfield/views/chartfield_view.xml

Module : pabi_chartfield
BG : แก้ไขหน้า Job Order View
Issues : https://mobileapp.nstda.or.th/redmine/issues/4281

#4281_Fix_Job_Order_view

---

pabi_partner_dunning_report/models/pabi_partner_dunning_letter.py

Module : pabi_partner_dunning_report
FI : user login แล้วมองไม่เห็นค่าของ validator
Issues : https://mobileapp.nstda.or.th/redmine/issues/4266

#4266_validator_field_Doc_type

---

pabi_partner_dunning_report/models/pabi_partner_dunning_report.py
pabi_partner_dunning_report/wizard/pabi_partner_dunning_wizard.py

Module: pabi_partner_dunning_report (Restart & Update This Only)
*แก้ไข domain dunning report ให้เช็ค reconcile_id & reconcile_partial_id
https://mobileapp.nstda.or.th/redmine/issues/4241

#4241-PartnerDunning

---

pabi_asset_management/models/asset.py

แก้ไขการคำนวณวันผิดเมื่อใช้ menu import asset batch

#4304 [FIX] compute asset line import batch

---

account_budget_activity/models/account_budget.py
pabi_budget_monitor/models/account_invoice.py
pabi_procurement/models/purchase.py
pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
purchase_invoice_plan/models/purchase_invoice_plan.py
purchase_invoice_plan/wizard/create_invoice.py

- แก้ไขให้ระบบ query `from budget_monitor_report`
แทน from แต่ละ module (res_project_monitor_view, res_section_monitor_view)
- แก้ไข code WA, Purchase Invoice Plan ให้เป็น best pattern
ผลการทดสอบ check budget
PR
15 -> 8 s
PO Confirm
6 -> 0.4 s
HR Expense
7.3 -> 4 s
INV
6 -> 0.4 s
IN Transfer -> Asset (10 assets)
93 -> 54 s
Deployment : restart only

#4314 [FIX] performance all of check budget

---

l10n_th_account/models/account_voucher.py

Issue: https://mobileapp.nstda.or.th/redmine/issues/4273
ปัญหาเกิดจากทศนิยมของ Python 
เมื่อลอง print ค่าของ amount_wht
Output:
ซึ่งเมื่อทำการปัดเศษค่าที่ได้ควรจะต้องเป็น -88.67
จึงได้แก้ไขโค๊ดส่วนดังกล่าว
reference: https://realpython.com/python-rounding/#rounding-half-up
หลังจากทำการแก้ไข
cc. @Saran440

[FIX] decimal rounding problem

---

pabi_account_move_adjustment/models/account.py

Module: pabi_account_move_adjustment (Restart&Update Module)
*แก้ไข move_line ให้ require AG&A เฉพาะ doc JV และ TP
https://mobileapp.nstda.or.th/redmine/issues/4318

#4318-Journal_item

---

pabi_account_report/reports/xlsx_report_cd_receivable_balance_sheet_detail.py

FI : รายงาน CD Receivable Balance Sheet Detail ไม่แสดงยอดยกมา
Issues : https://mobileapp.nstda.or.th/redmine/issues/4020

#4020_brought_forward_Report_CD

---

pabi_asset_management/views/asset_view.xml

module : pabi_asset_management
FI : เพิ่ม group หน้า Asset View
Issues : https://mobileapp.nstda.or.th/redmine/issues/4130

#4130_group_by_asset_view

---

account_budget_activity/models/purchase_request.py
pabi_procurement/models/purchase_web_interface.py

- เปลี่ยนการรับค่าจากระบบ Alfresco เข้าระบบ PABI2 โดยเปลี่ยน string เป็น id ของ field many2one
เพื่อลดการทำงานของ core odoo
ผลการทดสอบ
PR
8.5 -> 7.3 s

[FIX] performance convert string to id in PR

---

purchase_cash_on_delivery/models/account.py
purchase_cash_on_delivery/models/account_invoice.py
purchase_cash_on_delivery/views/account_view.xml

แก้ไขเพิ่ม config profit / loss  กรณีที่เกิดผลต่างแลกเปลี่ยนสกุลเงิน
deployment : restart and update module 'purchase_cash_on_delivery'

#3948 [FIX] clear prepaid config

---

pabi_forms/jrxml_reports/account/receipt_supplier_form.jrxml

FI : ใบรับเงินมีตัวอักษรสรุปยอดเงินมีทศนิยมเศษสตางค์
แต่ระบบไม่แสดงเศษสตางค์
Issues : https://mobileapp.nstda.or.th/redmine/issues/4370

#4370_text_amount

---

pabi_account/models/account_invoice.py
pabi_account/views/account_invoice_view.xml
pabi_validate_pricediff/models/invoice.py

- เปลี่ยนการคำนวณ currency จาก Posting Date (account.invoice)-> Transfer Date (stock.picking) เพื่อให้ระบบคำนวณด้วย rate ที่เท่ากัน
- แก้ไขให้ระบบแสดง exchange rate ที่หน้า supplier invoice
Deployment : restart and update module 'pabi_account'

#3948 [FIX] price diff currency rate

---

pabi_account/views/account_view.xml

Module : pabi_account
BI : Reconcile ID หน้า View ให้แสดง Creation date
Issues : https://mobileapp.nstda.or.th/redmine/issues/4297

#4297_Show_Field_In_Reconcile_ID

---

pabi_account/views/account_invoice_view.xml

Module : pabi_account
เพิ่ม Filter KV ให้มี Group by Currency
Issues : https://mobileapp.nstda.or.th/redmine/issues/4391

#4391_Add_GroupBy_Currency

---

pabi_account/views/account_invoice_view.xml
pabi_intray/data/asset_request_message.xml
pabi_intray/data/stock_request_message.xml

Module : pabi_intray	
แก้ไข Stock Request Status Confirmed ให้ is_complete เป็น True และเพิ่ม Message Cancel ใน Status Cancelled ชอง  Asset Request
Issues : https://mobileapp.nstda.or.th/redmine/issues/4294 , https://mobileapp.nstda.or.th/redmine/issues/4398

#4398 pabi intray message

---

pabi_account/views/account_invoice_view.xml

Module : pabi_account
เพิ่ม Filter KV ให้มี Group by Currency
Issues : https://mobileapp.nstda.or.th/redmine/issues/4391

#4391 add group by pull again

---

pabi_chartfield/models/chartfield.py

เมนู ฺExpenses >> Salary & Welfare >> Salary Expense
ใน Tab Detail กรณี Budget ที่มีหลาย Fund ให้เลือก Fund อันแรกของโครงการมาแสดง

multi fund - sale_expense

---

pabi_partner_dunning_report/__openerp__.py

Module: pabi_partner_dunning_report
*เพิ่ม ลายเซนในจดหมายติดตามหนี้ Dunning letter
https://mobileapp.nstda.or.th/redmine/issues/4406

#4406-DunningLetter

---

account_budget_activity/models/account_move_line.py

แก้ไขให้ระบบคำนวณ document ใน analytic_line อีกครั้งหนึ่งหลังจากสร้างเสร็จ
Deployment : Restart only

#4401 [FIX] recompute document in analytic_line

---

pabi_asset_management/models/asset_adjust.py

เมื่อกด post ใน journal ระบบจะ check budget โดยปกติแล้วระบบจะทำทีละบรรทัด ซึ่งตรงนี้ระบบดูจากฝั่งที่เพิ่ม budget ก่อน ทำให้ทุกครั้งระบบจะทำให้ budget *2 และเมื่อทำอีกครั้งหนึ่ง ระบบจะลดงบประมาณที่เพิ่มขึ้น
วิธีแก้ไขคือ เปลี่ยนให้ระบบลด budget เท่าจำนวนที่ใช้ก่อนแล้วค่อยเพิ่มกลับมาเท่าเดิม 
- จากเดิมระบบจะ post ก่อนแล้วค่อยแก้ไข analytic_line ทำให้ระบบ check budget ตั้งแต่ระบบ auto post แก้โดยการเปลี่ยนให้ระบบลด budget ออกไปก่อนแล้วค่อยเพิ่มกลับมาทีหลัง 
- ลด function ที่ไม่จำเป็นออกเพื่อให้ระบบทำงานได้ดีขึ้น
Deployment : Restart only

#4401 [FIX] adjust expense to asset and refactor code

---

pabi_hr_expense/views/hr_expense_view.xml

Module : pabi_hr_expense
FI : เพิ่มเงื่อนไขเป็น
Wait for Accept (Past FY) = (ปีของ Approved Date ตกอยู่ใน ปีงบประมาณอดีตที่ผ่านมา)
Wait for Accept (Current FY) = (ปีของ Approved Date ตกอยู่ใน ปีงบประมาณปัจจุบัน)
Issues: https://mobileapp.nstda.or.th/redmine/issues/4402

#4402 edit filter on expense

---

l10n_th_account/views/account_wht_cert.xml

Module : l10n_th_account
FI : เพิ่มเงื่อนไขใน Group by ให้ filter myWHT to
Issues : https://mobileapp.nstda.or.th/redmine/issues/4431

#4431_myWHT_filter_status_done

---

pabi_forms/jrxml_reports/account/receipt_supplier_form.jrxml

FI : ใบรับเงินมีตัวอักษรสรุปยอดเงินมีทศนิยมเศษสตางค์
แต่ระบบไม่แสดงเศษสตางค์
Issues : https://mobileapp.nstda.or.th/redmine/issues/4370

#4370_text_amount_fix

---

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
pabi_tax_rounding/models/purchase_work_acceptance.py

How to change?
- Find keywork "depends" and replace to "constrains"
- Sub field will not work, i.e., @api.constrains('line_ids.status'),
Change to @api.constrains('line_ids')
- Make sure you find all possible inherited function, and change it too

[ENH] Work Acceptance, performance by api.depends to api.constrains

---

pabi_budget_transfer/models/section_budget_transfer.py

แก้ไขการคำนวณ Transfer Amount = Release – Consumed (ยอด ฺBalance ในหน้าจอ Budget Monitor ที่ budget_method = “expense”)

#4405 [FIX] transfer_amount

---

pabi_forms/qweb_reports/account/layouts.xml

FI : Rate ใน voucher KV - Supplier invoice ผิด
Issues : https://mobileapp.nstda.or.th/redmine/issues/4433

#4433_edit_form_invoice_voucher_qweb

---

pabi_forms/qweb_reports/account/layouts.xml

Module: pabi_forms (Restart & Update Module)
แก้ไข ทศนิยมของ currency rate
https://mobileapp.nstda.or.th/redmine/issues/4433

#4433-PrintVoucher

---

pabi_forms/qweb_reports/account/layouts.xml

Module: pabi_forms (Restart & Update Module)
แก้ไข error Print voucher currency_rate
https://mobileapp.nstda.or.th/redmine/issues/4451

#4451-ErrorVoucher

---

account_budget_activity/models/purchase_request.py

แก้ไขการ check rules ใน lines ของ pr lines
ให้ระบบตรวจสอบ rules จาก pr ก่อน ซึ่งถ้าสามารถผ่านได้
ใน pr lines ก็ควรจะผ่านได้โดยไม่ต้อง check rules อีกครั้งหนึ่ง
เพราะมีการเขียน rules เหมือนกัน จึงใช้ .sudo() เพื่อผ่านการ check rules ใน pr lines
ผลการทดสอบ
ก่อนใช้ .sudo() -> 4 s
หลังใช้ .sudo() -> 0.2 s

#4467 [FIX] performance PR

---

pabi_etl/models/etl_budget_view.py

ADD res_project_revenue_actual.actual_amount in view : etl_issi_budget_project_query

#4472 add res_project_revenue_actual in view : etl_issi_budget_project_query

---

pabi_account/models/account_invoice.py
pabi_asset_management/models/asset_adjust.py
pabi_asset_management/wizard/create_asset_adjust_wizard.py

แก้ไขให้ระบบทำการแปลงค่าเงิน กรณีที่มีการทำ asset adjust ที่หน้า invoice

#4524 [FIX] convert currency to asset adjust

---

pabi_etl/models/etl_budget_view.py

Edit join condition in view issi_.budget_project_monitor_view -> summary each project `actaul` revenue 1 row per fiscal year

Edit view: issi_.budget_project_monitor_view

---

pabi_account_report/reports/xlsx_report_cd_receivable_balance_sheet_detail.py
pabi_account_report/xlsx_template/templates.xml

FI : ยอดคงเหลือยังไม่ถูกต้อง
Issues : https://mobileapp.nstda.or.th/redmine/issues/4020

#4020_outstanding_Report_CD

---

pabi_budget_internal_charge/models/hr_expense.py

เพิ่ม index เพื่อให้ระบบทำงานเร็วขึ้น (มีผลเล็กน้อย)
แต่สาเหตุหลักที่ช้าคือ
- ระบบสร้าง journal entries ทั้งฝั่ง revenue และ expense
- ระบบสร่าง account_analytic_line โดย 1 journal/2 analytic_line (ตัดและคืน budget)
deployment : restart and update module 'pabi_budget_internal_charge'

[FIX] performance hr internal charge

---

pabi_account_report/reports/asset_estimate_report.py

Module: pabi_account_report (Restart Only)
*ปรับแก้เงื่อนไขรายงาน
https://mobileapp.nstda.or.th/redmine/issues/4535

#4535-AssetEstimateReport

---

pabi_async_process/__init__.py
pabi_async_process/__openerp__.py
pabi_async_process/action_hr_expense_create_multi_supplier_invoices/__init__.py
pabi_async_process/action_hr_expense_create_multi_supplier_invoices/expense_create_multi_supplier_invoice.py
pabi_async_process/action_hr_expense_create_multi_supplier_invoices/expense_create_multi_supplier_invoice_view.xml
pabi_async_process/action_hr_expense_create_multi_supplier_invoices/pabi_process.xml

Issue: https://mobileapp.nstda.or.th/redmine/issues/4528
Deployment: Restart & Update This Only "pabi_async_process"
เพิ่ม "Run task in background?" ที่หน้า Create Supplier Invoice ที่มี User Attendee List
สำหรับกรณีมีหลายรายการ

#4528 - [ADD] Run Job - Create Multi Supplier Invoice

---

pabi_asset_management/models/asset.py

แก้ไขการคำนวณ asset line จากการ import asset

#4542 [FIX] import asset compute

---

pabi_partner_dunning_report/models/pabi_partner_dunning_letter.py

Module: pabi_partner_dunning_report (Restart & Update module)
แก้ไข fields date_due ให้ fix ตาม date_due ณ วันที่รัน Dunning Report
https://mobileapp.nstda.or.th/redmine/issues/4023

#4023-DunningLetter

---

pabi_asset_management/models/asset_adjust.py

Issue: https://mobileapp.nstda.or.th/redmine/issues/4487
deployment: Restart
เมื่อ Cancel ASJ จาก Asset -> Asset , Expense -> Asset 
แก้ไข Asset Status จาก "ยกเลิก" เป็น "ยกเลิกครุภัณฑ์"

#4487 - Cancel ASJ แล้วยกเลิก asset ให้ปรับ asset status เป็นยกเลิกครุภัณฑ์

---

pabi_validate_pricediff/models/invoice.py

แก้ปัญหาจาก User ไม่มีสิทธิ์เข้าถึงมูล จึงเปลี่ยน User เป็น Superuser เมื่อเรียกใช้ฟังก์ชัน

#4543 - Change uid to Superuser

---

pabi_account_move_adjustment/wizard/create_journal_entry_wizard.py
pabi_account_move_adjustment/wizard/create_journal_entry_wizard.xml

Module : pabi_account_move_adjustment
FI : เพิ่มเนู Create Adjustment Journal ใน Doc SL
Issues : https://mobileapp.nstda.or.th/redmine/issues/4403

#4403_add_create_adjustment_journal_on_hr_salary_expense

---

pabi_partner_dunning_report/models/pabi_dunning_config.py
pabi_partner_dunning_report/models/pabi_partner_dunning_letter.py
pabi_partner_dunning_report/report/layouts.xml
pabi_partner_dunning_report/views/pabi_dunning_config.xml

Module: pabi_partner_dunning_report (Restart & Update Module)
แก้ไข template รายงานให้เช็คการดึงลายเซ็นจากฟิลด์ Use Signature Image
https://mobileapp.nstda.or.th/redmine/issues/4568

#4568-DunningLetter

---

pabi_interface/models/interface_account.py

เพิ่มการทำงานให้ระบบ auto reconcile
ปกติระบบจะ auto reconcile เมื่อทำการ reverse เท่านั้น
ฉะนั้นจึงทำการเพิ่ม auto reconcile เมื่อเกิดกรณีดังนี้
- ส่งค่า reconcile_move_id

#4553 [ADD] function auto reconcile in interface

---

pabi_interface/models/interface_account.py

แก้ไขให้ระบบรองรับการทำ reconcile หลาย journal จากการทำ interface

#4586 [FIX] support multi reconcile

---

account_budget_activity/models/budget_commit.py
l10n_th_account/models/account_voucher.py
l10n_th_account/views/voucher_payment_receipt_view.xml

https://mobileapp.nstda.or.th/redmine/issues/4583
deployment: restart & update this only module: "l10n_th_account"
หากแก้ที่ตัวระบบอาจส่งผลกระทบต่อ การทำงานอื่นๆ จึงเพิ่ม field: "Update Tax"
หากทำการเลือก ระบบจะอัพเดท Tax ทุกครั้งที่มีการ save 
หากระบบดึงข้อมูลที่ผิดมา ให้ทำการ Edit แล้วลบข้อมูลที่ผิด แล้วเลือก Update Tax ออก

#4583 - Add field is_update

---

pabi_procurement/models/purchase_web_interface.py

ลบการแปลง string -> id ใน field request_ref_id เพราะยังไม่สร้างในระบบ odoo

#4592 [FIX] interface PR convert string to id

---

l10n_th_account/__openerp__.py
l10n_th_account/data/ir_cron_data.xml
l10n_th_account/models/account_wht_cert.py

Module : l10n_th_account
FI : เพิ่ม job การส่ง email อัตโนมัติของ Email WHT Cer
Issues : https://mobileapp.nstda.or.th/redmine/issues/4530

#4530_send_mail_wht_job

---

account_budget_activity/models/budget_commit.py
pabi_budget_internal_charge/models/hr_expense.py

https://mobileapp.nstda.or.th/redmine/issues/4570
deployment: Restart
แก้ไขให้เมื่อ สร้าง Expense เลือก Pay Type: Internal Charge ระบบจะสร้าง Budget Commit มี Type เป็น Internal
เมื่อทำการ เบิกจ่ายแล้วระบบจะ Clear Budget Commit

Fix - Error 4570

---

pabi_purchase_billing/models/purchase_billing.py

Issue: https://mobileapp.nstda.or.th/redmine/issues/4545
กรณี PO ยังมี IN ที่ยังไม่เป็นสถานะ Transferred เมื่อทำการกด Validate ที่ Purchase Billing ระบบขึ้นแจ้งเตือน

#4545 - Add_validate_error_in_purhcase_billing

---

account_budget_activity/models/budget_commit.py

แก้ไขให้ระบบทำ internal เฉพาะ EX

#4570 [FIX] budget internal

---

pabi_asset_management/models/asset_changeowner.py

Module : pabi_asset_managerment
PO : ปรับแก้ไขการ Change Owner Asset ให้สามารถเลือกรายการที่มี State เป็น Close
Issues : https://mobileapp.nstda.or.th/redmine/issues/4598

#4598_change_domain_status_asset_id

---

pabi_etl/models/etl_budget_view.py

-- 1. etl_issi_budget_investment_asset_query
-- 2. etl_issi_m_investment_asset

add new 2 views

---

pabi_account_gl_jasper/__init__.py
pabi_account_gl_jasper/__openerp__.py
pabi_account_gl_jasper/data/jasper_data.xml
pabi_account_gl_jasper/reports/__init__.py
pabi_account_gl_jasper/reports/jasper_report_journal_document_entry.py
pabi_account_gl_jasper/reports/jasper_report_journal_document_entry.xml
pabi_account_gl_jasper/reports/report_journal_document_entry.jrxml
pabi_account_gl_jasper/security/ir.model.access.csv

Module : pabi_account_gl_jasper
FI: พัฒนารายงาน Journal Document Entry
Issues : https://mobileapp.nstda.or.th/redmine/issues/4276

#4276_Journal_Document_Entry

---

account_budget_activity/models/budget_commit.py
account_budget_activity/views/hr_expense_view.xml
account_budget_activity/views/purchase_request_view.xml
account_budget_activity/views/purchase_view.xml
account_budget_activity/views/sale_view.xml
account_budget_activity/wizard/budget_technical_close.py
account_budget_activity/wizard/budget_technical_close.xml

Module : account_budget_activity
PO : ขอเพิ่มและแสดงเหตุผลในการ Close & Uncommit Budget หน้า PR/PO
Issues : https://mobileapp.nstda.or.th/redmine/issues/4516

#4516 add close&uncommit budget pr/po

---

pabi_etl/models/etl_budget_view.py

fix sql's syntax when create view

#4449 add etl budget view

---

pabi_etl/models/etl_budget_view.py

แก้ไขรายได้(External)ของโครงการในปีเก่าก่อนขึ้นระบบ PABI2 (<2018)
https://mobileapp.nstda.or.th/redmine/issues/4449

edit view : issi_budget_project_monitor_view

---

pabi_budget_internal_charge/models/hr_expense.py
pabi_budget_monitor/models/hr_expense.py

แก้ไขให้ระบบรองรับการ check budget internal เมื่อมีการติ๊ก control_ext_charge_only ออก

#4606 [FIX] check budget internal

---

pabi_etl/models/etl_budget_view.py

Edit sql conditions project's revenue

Edit old project's revenue

---

pabi_budget_internal_charge/models/hr_expense.py

แก้ไข error เมื่อมีการ print Advance Dunning letter

[FIX] bug internal budget

---

pabi_forms/jrxml_reports/procurement/purchase_order_EN.jrxml
pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

PO : ปรับแก้ไขรูปแบบหมายเลขโทรศัพท์ แฟกซ์ ในเอกสาร PO
Issues : https://mobileapp.nstda.or.th/redmine/issues/4515

#4515_edit_from_phonenumber

---

pabi_account_gl_jasper/reports/report_journal_document_entry.jrxml

Module : pabi_account_gl_jasper (restart only)
FI : รายงาน Journal Document ช่อง AG ไม่ถูกต้อง
Issues : https://mobileapp.nstda.or.th/redmine/issues/4645

#4645_AG_Name_Journal_Document

---

pabi_budget_plan_monitor/models/budget_plan_unit.py

แก้ไขให้ระบบตรวจสอบ charge type จาก monitor report
deployment : restart and update module 'pabi_budget_plan_monitor'

#4600 [FIX] unit base charge_type

---

pabi_forms/jrxml_reports/procurement/purchase_order_EN.jrxml

(แก้ไขเพิ่มเติม)
PO : แก้ไขการแสดงผลทศนิยม กับ ลำดับรายการ ใน Purchase Order ENG (PDF)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4651

#4651_Fix_Purchase_Order_ENG

---

pabi_base/models/product.py
pabi_base/views/menu_view.xml

Module : pabi_base
PO : Product master เก็บ history Inventory Valuation
Issues : https://mobileapp.nstda.or.th/redmine/issues/4595

#4595_product_master_add_history_inventory_valuation

---

pabi_validate_pricediff/models/invoice.py

ทำการแก้ไข error pricediff ที่ Module pabi_validate_pricediff

[8.0][edit]_Error_pricediff

---

pabi_budget_fund_rule/models/budget_fund_rule.py

BG : ปรับแก้ Filter Search Account ในหน้าจอ myProject Fund Rule
Module : pabi_budget_fund_rule (restart only)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4693

#4693_Filter_Search_Account

---

account_budget_activity/models/account.py

FI : Bank Journals เวลา Create ให้ default Analytic Journal เป็น General Budget
Module : account_budget_activity (restart only)
Issues : https://mobileapp.nstda.or.th/redmine/issues/4677

#4677_Bank_Journals_Default_Analytic

---

account_trial_balance_report/models/trial_balance_report.py

แก้ไขการ query  ที่ report trial balance ที่ inactive ด้วย
สาเหตุเกิดจากมี 2 move line ที่มี journal inactive ไปแล้ว
ทำให้ระบบไม่ได้ query ข้อมูล 2 lines นั้นมาด้วย เลยทำให้ค่า debit ผิด

[FIX] report trial balance not query inactive journal

---

pabi_chartfield/__openerp__.py
pabi_chartfield/models/sale.py
pabi_chartfield/views/sale_view.xml
pabi_chartfield/wizard/__init__.py
pabi_chartfield/wizard/change_invoice_date_wizard.py
pabi_chartfield/wizard/change_invoice_date_wizard_view.xml

Module : pabi_chartfield
FI : Sale order ขอเพิ่มเมนู และหน้าต่างการ update วันที่
Redmine : https://mobileapp.nstda.or.th/redmine/issues/3589

#3589_Change_Invoice_Date_New

---

pabi_account/models/account_bank_receipt.py

Issue : https://mobileapp.nstda.or.th/redmine/issues/4625
เพิ่ม function สำหรับการตัด budget ย้อนหลัง

[ADD] recompute check budget in bank receipt

---

pabi_budget_monitor/views/res_fund_view.xml

BG : ลบ Tab ที่แสดงข้อมูล Budget Monitor ออกจากหน้าจอ Source of Funds
Module : pabi_budget_monitor
Issues : https://mobileapp.nstda.or.th/redmine/issues/4728

#4728_Delete_Tab_Budget_Monitor_in_Source_of_funds_NEW

---

pabi_account/models/account_voucher.py

เพิ่มให้ระบบรองรับการ recompute budget เหมือนกับ bank receipt
โดยใช้ function เดียวกันคือ action_recompute_budget
issue : https://mobileapp.nstda.or.th/redmine/issues/4732

[ADD] recompute budget in PV and DV

---

pabi_asset_import_batch/models/asset_import_batch.py
pabi_asset_management/wizard/stock_transfer_details.py
pabi_stock_transfer_detail/__init__.py
pabi_stock_transfer_detail/models/__init__.py
pabi_stock_transfer_detail/models/stock.py
pabi_stock_transfer_detail/wizard/stock_transfer_details.py
pabi_stock_transfer_detail/wizard/stock_transfer_details.xml

แก้ไขให้ระบบตรวจสอบ purchase value ของ asset ก่อน
ถ้าไม่มีค่า ระบบจะแจ้ง error 
deployment : restart and update module  pabi_stock_transfer_detail

#4699 [ADD] price_unit in stock_transfer

---

account_budget_activity/models/account.py
pabi_asset_management/models/asset_adjust.py

แก้ไขให้ระบบ update document ใน analytic เมื่อทำการ adjust asset

#4565 [FIX] update document in analytic line

---

pabi_asset_management/models/asset_removal.py

แก้ไขให้ระบบ update ค่า day ใน asset line เพื่อให้ตัวเลขเท่ากัน

[FIX] compute day_line in asset

---

pabi_budget_plan_monitor/models/budget_plan_unit.py

ระบบจะคำนวณโดยดู commit จากปีปัจจุบัน หากไม่เหลือระบบก็จะไม่ยกยอดมาให้
ทำให้ข้อมูลบางรายการหายไป
แก้ไขให้ระบบคำนวณเหมือนเดิม และมีการตรวจสอบเพิ่มเติม
กรณีที่มี budget เหลือของปีที่วางแพลน แต่ไม่มีงบเหลือในปีปัจจุบัน ให้นำมาแสดงด้วย

#4734 [FIX] budget prev year 0 but there are plan

---

pabi_forms/jrxml_reports/account/customer_tax_receipt.jrxml

แก้ไข Form ให้ระบบแสดงค่าเหมือนกับ tax receipt 200%
issue : https://mobileapp.nstda.or.th/redmine/issues/4700

#4700 [FIX] customer tax receipt form

---

purchase_invoice_plan/models/__init__.py
purchase_invoice_plan/models/stock.py

แก้ไขให้ระบบ บันทึก move_id ที่ invoice line เมื่อมีการทำ invoice_plan

[ENH] update move_id in invoice_line of create from invoice plan

---

pabi_asset_management/models/asset_adjust.py

แก้ไขให้ตรวจสอบ ค่าตัวแปรก่อน ถ้าไม่มีจะไม่ทำงาน
ซึ่งจะได้ไม่เกิด error ครับ
issue : https://mobileapp.nstda.or.th/redmine/issues/4777

#4777 [FIX] adjust error when split

---

pabi_pos/models/pos_web_interface.py
pabi_pos/models/stock.py

#4781-POS_InterfaceStock
**ตรวจสอบเช็ค Stock คงเหลือในระบบ PABI2 เมื่อ Interface ผ่าน POS
https://mobileapp.nstda.or.th/redmine/issues/4781

#4781-POS_InterfaceStock

---

pabi_asset_import_batch/models/asset_import_batch.py

แก้ไขกรณีที่ระบบ search หาได้มากกว่า 1

[FIX] import asset singleton

---

payment_export/models/register_icash.py
payment_export/report/register_icash_report.py
payment_export/views/register_icash_view.xml

Module: payment_export (Restart & Update Module)
*เพิ่ม Config การ create doc และ Exported 
issue : https://mobileapp.nstda.or.th/redmine/issues/4801

#4801-PreRegisterConfig

---

pabi_forms/jrxml_reports/procurement/call_for_bids_1.jrxml

Module : pabi_forms (restart only)
PO : ข้อมูลจำนวนในแบบฟอร์ม Call for Bids (PD) แสดงรายละเอียดไม่ครบถ้วน
Issues : https://mobileapp.nstda.or.th/redmine/issues/4778

#4778_Call_for_Bids_Quantity

---

pabi_apps_config/views/pabi_menu_config.xml
payment_export/views/register_icash_view.xml

Issue : https://mobileapp.nstda.or.th/redmine/issues/4801
update only 3 module
- payment_export
- pabi_apps_config
- pabi_etl

4788 fix 4801

---

pabi_forms/qweb_reports/account/layouts.xml

Module : pabi_forms (restart and update)
FI : ขอเพิ่มชื่อบัญชี ภาษาไทย ใน Voucher PV
Issues : https://mobileapp.nstda.or.th/redmine/issues/4798

#4798_Add_Bank_Owner_Name_Voucher_PV

---

pabi_account_report/reports/asset_register_report.py
pabi_account_report/reports/asset_register_report.xml

FI : รายงาน Asset Register ให้ตรวจสอบ Tab เงื่อนไข Asset Filter
deployment : restart and update
Issues : https://mobileapp.nstda.or.th/redmine/issues/4719

#4719_Fix_Tab_Asset_Filter_NEW

---

pabi_pos/models/pos_web_interface.py

https://mobileapp.nstda.or.th/redmine/issues/4840

#4840-POS_Interface

---

pabi_asset_import_batch/__openerp__.py
pabi_asset_import_batch/models/__init__.py
pabi_asset_import_batch/models/asset.py
pabi_asset_import_batch/models/asset_import_batch.py
pabi_asset_import_batch/views/asset_view.xml

Add field "is_import" to master asset

4830 add asset import field

---

payment_export/models/register_icash.py
payment_export/views/register_icash_view.xml

Module: payment_export (Restart & Update Module)
issue : https://mobileapp.nstda.or.th/redmine/issues/4801

#4801-PreRegister_iCash

---

pabi_asset_management/models/asset_transfer.py
pabi_asset_management/views/asset_transfer_view.xml

เพิ่ม Transfer แบบใช้ job 
deployment : restart and update module 'pabi_asset_management' (ใช้เวลา update ประมาณ 20 นาที)

[ADD] job asset transfer

---

pabi_etl/models/issi_account_view.py
pabi_etl/models/issi_master_view.py

add 3 new views  
- issi_selection_org_view
- issi_selection_program_view
- etl_issi_account_query

#4858 add budget view

---

payment_export/models/register_icash.py

Branch: #4801-PreRegisteriCash
Module: payment_export (Restart Only)
https://mobileapp.nstda.or.th/redmine/issues/4801

#4801-PreRegisteriCash

---

ir_test_action/wizard/ir_test_action.py
ir_test_action/wizard/ir_test_action_view.xml

Branch: #4730-ComputeDepreAsset
Module: ir_test_action (Restart & Update Module)
https://mobileapp.nstda.or.th/redmine/issues/4730

#4730-ComputeDepreAsset

---

stock_request/models/stock.py
stock_request/models/stock_request.py
stock_request/views/stock_view.xml

เพิ่มการตั้งค่าใน stock.location เมื่อทำการ request ระบบจะ update value costcenter และ section ให้ในฝั่ง credit 
deployment : restart and update module 'stock_request'

#4845 [ADD] section in location stock_request

---

pabi_purchase_work_acceptance/models/purchase_work_acceptance.py

แก้ไขให้ระบบตรวจสอบทั้ง service และ storeable

#4873 [FIX] qty check service

---

pabi_asset_import_batch/models/asset_export_report.py

FI : Asset Import เวลาเลือก Asset บางส่วนระบบ asset ให้ทั้งหมด
Module : pabi_asset_import_batch
Issues : https://mobileapp.nstda.or.th/redmine/issues/4891

#4891_Fix_Asset_Import

---

pabi_budget_transfer/models/section_budget_transfer.py
pabi_budget_transfer/views/section_budget_transfer_view.xml
pabi_intray/data/budget_transfer_message.xml

- แก้ไขเรื่องการ filter budget ให้ดูได้หลาย org
- แก้ไขให้ org มาได้มากกว่า 1
- เปลี่ยนชื่อ field จาก org_id > org_ids
deployment : restart and update module 'pabi_budget_transfer' and 'pabi_intray'

#4890 [FIX] org_id filtered from budget

---

pabi_account/__openerp__.py
pabi_account/data/email_template.xml
pabi_account/data/ir_cron_data.xml
pabi_account/data/report_data.xml
pabi_account/models/account_config_settings.py
pabi_account/models/account_voucher.py
pabi_account/models/res_company.py
pabi_account/views/account_voucher_view.xml
pabi_apps_config/models/pabi_apps_config.py
pabi_apps_config/views/pabi_apps_config.xml

FI : ทำระบบส่งเมล์อัตโนมัติ ใบรับเงิน สำหรับรับคืนเงินยืมทดรองจ่ายของ
ให้พนักงาน
Module : pabi_account,pabi_apps_config
Issues : https://mobileapp.nstda.or.th/redmine/issues/4632
deployment : restart and update 2 modules

#4632_mail_receipt_voucher_auto_send_new

---

pabi_asset_management/wizard/stock_transfer_details.py
pabi_stock_transfer_detail/wizard/stock_transfer_details.py

แก้ไขให้ระบบ filtered หน่วยนับ

[FIX] Uom stock

---

account_budget_activity/models/account_budget.py
pabi_budget_internal_charge/models/account_budget.py

แก้ไขการทำงานให้ Past Actual เป็นเหมือนเดิม
คือ คำนวณเฉพาะ actual

#4928 [FIX] Rollback query past actual

---

pabi_apps_config/views/pabi_menu_config.xml
pabi_budget_internal_charge/models/hr_expense.py
pabi_budget_internal_charge/security/security_rule.xml
pabi_budget_internal_charge/views/hr_expense_view.xml
pabi_forms/__init__.py
pabi_forms/__openerp__.py
pabi_forms/data/account_data.xml
pabi_forms/jrxml_reports/account/receipt_internal_charge_form.jrxml
pabi_forms/print_internal_charge/__init__.py
pabi_forms/print_internal_charge/print_internal_charge_parser.py
pabi_forms/print_internal_charge/print_internal_charge_wizard.py
pabi_forms/print_internal_charge/print_internal_charge_wizard.xml

FI : สร้างแบบฟอร์มใบเสร็จรับเงินบน EX internal charge
Module : pabi_forms, pabi_budget_internal_charge,pabi_apps_config
Issues : https://mobileapp.nstda.or.th/redmine/issues/4628

#4628_EX_Internal_Charge_receipt

---

pabi_account_gl_jasper/__openerp__.py
pabi_account_gl_jasper/data/jasper_data.xml
pabi_account_gl_jasper/reports/__init__.py
pabi_account_gl_jasper/reports/jasper_asset_register_report.py
pabi_account_gl_jasper/reports/jasper_asset_register_report.xml
pabi_account_gl_jasper/reports/report_asset_register.jrxml
pabi_apps_config/views/pabi_menu_config.xml

FI: พัฒนารายงาน Asset Register Report ในรูปแบบของ jasper report
Module : pabi_account_gl_jasper,pabi_apps_config
Issues : https://mobileapp.nstda.or.th/redmine/issues/4774
deployment : restart and update only

#4774_Asset_Register_Jasper_Report

---

pabi_my_project/models/res_project.py

Branch: #ProjectReleaseExpense
Module: pabi_my_project (Restart Only)

#ProjectReleaseExpense

---

pabi_budget_internal_charge/views/hr_expense_view.xml

FI : แก้ไข Filter หน้า Expense
Module : pabi_budget_internal_charge
Issues : https://mobileapp.nstda.or.th/redmine/issues/4947

#4947_Fix_Filter_Expense

---

pabi_budget_internal_charge/models/ic_picking_web_interface.py

Branch: #4892-CheckInterfaceStockSection
Module: pabi_budget_internal_charge (Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/4892

#4892-CheckInterfaceStockSection

---

account_budget_activity/models/account_budget.py
pabi_budget_interface/models/budget_web_interface.py

Branch: #4913-CheckBudget
Module: account_budget_activity,pabi_budget_interface (Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/4913

#4913-CheckBudget

---

pabi_budget_interface/models/budget_web_interface.py

Branch: #4913-CheckBudgetReverse
Module: pabi_budget_interface (Restart Only)
** แก้ไข code กลับไปเป็นเหมือนเดิม เนื่องจากเกิด error

#4913-CheckBudgetReverse

---

account_budget_activity/models/account_budget.py

Branch: #ReverseCodeBudget
Module: account_budget_activity (Restart Only)

#ReverseCodeBudget

---

pabi_account_asset_jasper/__init__.py
pabi_account_asset_jasper/__openerp__.py
pabi_account_asset_jasper/data/jasper_data.xml
pabi_account_asset_jasper/reports/__init__.py
pabi_account_asset_jasper/reports/jasper_report_asset_inactive_owner.py
pabi_account_asset_jasper/reports/jasper_report_asset_inactive_owner.xml
pabi_account_asset_jasper/reports/report_asset_inactive_owner.jrxml
pabi_account_asset_jasper/security/ir.model.access.csv
pabi_apps_config/views/pabi_menu_config.xml

FI : พัฒนารายงาน Asset Inactive Owner Report
Module : pabi_account_asset_jasper, pabi_apps_config
Issues : https://mobileapp.nstda.or.th/redmine/issues/4836

#4836_Asset_Inactive_Owner_Report

---

pabi_budget_interface/models/budget_web_interface.py
pabi_budget_internal_charge/models/ic_picking_web_interface.py

Branch: #4913-CheckBudget_new
Module: pabi_budget_interface,pabi_budget_internal_charge (Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/4913

#4913-CheckBudget_new

---

pabi_budget_drilldown_report/models/analytic.py

แก้ไขให้ user สามารถมองเห็น account code, account name ได้
issue : https://mobileapp.nstda.or.th/redmine/issues/4985?issue_count=8&issue_position=1&next_issue_id=4902

#4985 [FIX] compute not sudo

---

pabi_purchase_billing/models/purchase_billing.py

แก้ไขให้ระบบ check IN เมื่อทำ purchase billing ด้วย purchase ที่ไม่ใช่ invoice plan

#5011 [FIX] condition check validate billing not invoice_plan

---

pabi_purchase_work_acceptance/__openerp__.py
pabi_purchase_work_acceptance/wizard/__init__.py
pabi_purchase_work_acceptance/wizard/update_wa_invoice.py
pabi_purchase_work_acceptance/wizard/update_wa_invoice.xml

แก้ไขในกรณีที่มีการทำ PO INV ค้าง (เอกสารใบเก่า)
Deployment : restart and update module 'pabi_purchase_work_acceptance'
issue : https://mobileapp.nstda.or.th/redmine/issues/5017?issue_count=25&issue_position=1&next_issue_id=4996

#5017 [FIX] update wa invoice old document

---

pabi_purchase_work_acceptance/wizard/create_purchase_work_acceptance.py

#5025 [FIX] purchase_work_acceptance fix error

---

res_partner_ext/models/partner.py
res_partner_ext/views/partner_view.xml

Branch: #5024-add-email-etax
Module: res_partner_ext (Restart & Update Module)
Issue: https://mobileapp.nstda.or.th/redmine/issues/5024

#5024-add-email-etax

---

pabi_budget_drilldown_report/models/budget_drilldown_report.py
pabi_budget_drilldown_report/models/common.py
pabi_budget_drilldown_report/views/budget_all_report.xml
pabi_budget_drilldown_report/views/budget_drilldown_common.xml
pabi_budget_drilldown_report/views/budget_invest_asset_report.xml
pabi_budget_drilldown_report/views/budget_invest_construction_report.xml
pabi_budget_drilldown_report/views/budget_overall_report.xml
pabi_budget_drilldown_report/views/budget_project_base_report.xml
pabi_budget_drilldown_report/views/budget_unit_base_report.xml
pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.py
pabi_budget_drilldown_report/wizard/budget_drilldown_report_wizard.xml
pabi_budget_monitor/report/budget_monitor_report_view.xml
pabi_budget_monitor/report/budget_monitor_report_wizard.py
pabi_budget_monitor/report/budget_monitor_report_wizard_view.xml

เพิ่มการ filter / groupby ด้วย Job Order และ Job Order Type ใน Monitoring และ Overview Report
deployment : restart and update module
- pabi_budget_drilldown_report
- pabi_budget_monitor

#5029 [IMP] add job order to monitoring and overview report

---

pabi_forms/jrxml_reports/procurement/purchase_order_EN.jrxml
pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

Branch: #4513-PO_report
Module: pabi_forms(Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/4513
*ปรับ code เนื่องจากมี Conflict

#4513-PO_report

---

pabi_purchase_billing/views/account_invoice_view.xml
pabi_purchase_billing/views/purchase_billing_view.xml
pabi_purchase_work_acceptance/models/purchase_work_acceptance.py
pabi_purchase_work_acceptance/views/account_invoice_view.xml
pabi_purchase_work_acceptance/views/purchase_work_acceptance_view.xml

- เพิ่ม field และการเรียงลำดับที่หน้า Purchase Work Acceptance
- เปลี่ยนการ search ที่หน้า purchase billing
deployment : restart and update module
- pabi_purchase_billing
- pabi_purchase_work_acceptance 
issue : https://mobileapp.nstda.or.th/redmine/issues/5021

#5021 [IMP] work_acceptance tree view and purchase billing

---

pabi_account_move_adjustment/views/account_move_priority_view.xml

เพิ่ม field Job Order ให้แสดงที่หน้า account move line
deployment : update module pabi_account_move_adjustment

#5037 [FIX] add cost_control_id in move_line

---

pabi_account_gl_jasper/reports/jasper_report_journal_document_entry.py
pabi_account_gl_jasper/reports/jasper_report_journal_document_entry.xml
pabi_account_gl_jasper/reports/report_asset_register.jrxml
pabi_account_gl_jasper/reports/report_journal_document_entry.jrxml

FI : เพิ่ม Field ใน รายงาน Journal Entry Document
Module : pabi_account_gl_jasper
Issues : https://mobileapp.nstda.or.th/redmine/issues/5036
deployment : restart and update only

#5036_add_balance_journal

---

stock_request/models/stock_request.py

Branch: #4518-CheckProductOnHand
Module: stock_request(Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/4518

#4518-CheckProductOnHand

---

pabi_account_report/reports/xlsx_report_tax_exemption_receipt.py
pabi_account_report/reports/xlsx_report_tax_exemption_receipt.xml

Branch: #5031-ReportTaxExemption
Module: pabi_account_report(Restart & Update Module)
Issue: https://mobileapp.nstda.or.th/redmine/issues/5031

#5031-ReportTaxExemption

---

pabi_etl/models/etl_budget_view.py

Edited 4  Views
1. issi_res_project_budget_summary_view
2. issi_budget_project_monitor_view
3. etl_issi_budget_project_query
4. issi_budget_project_plan_view

##4955_edit_project_query_view

---

pabi_account_move_adjustment/models/account.py
pabi_account_move_adjustment/views/account_move_priority_view.xml
pabi_budget_monitor/models/account.py

แก้ไขการ check budget ในกรณีสร้างตรง หรือมาจากการ adjustment
deployment : restart and update module pabi_account_move_adjustment

#5046 [FIX] check budget adjustment

---

pabi_forms/jrxml_reports/procurement/purchase_order_EN.jrxml
pabi_forms/jrxml_reports/procurement/purchase_order_TH.jrxml

แก้ไข form purchase order (TH/EN)
ให้แสดงจำนวนรายการให้ถูกต้อง
และภาษาอังกฤษออกปีเป็น ค.ศ.
PO : พิมพ์ PO ต่างประเทศ ถ้ามีหลายๆ หน้า พบว่า ลำดับที่ไม่ถูกต้อง และ วันที่ให้แสดงปี ค.ศ.
https://mobileapp.nstda.or.th/redmine/issues/5051

#5051 [FIX] count number PO (TH/EN)

---

l10n_th_account_pit/models/account_pit.py
l10n_th_account_pit/models/account_voucher.py
l10n_th_account_pit/models/res_partner.py

แก้ไขการแสดงบรรทัดใน pit
กรณีที่มีการยกเลิก voucher ระบบจะไม่แสดงใน pit
deployment : restart and update module l10n_th_account_pit
issue : https://mobileapp.nstda.or.th/redmine/issues/5042

#5042 [FIX] account pit cancel

---

pabi_chartfield/views/account_budget_view.xml

แก้ไข error menu ไม่ถูกที่
update module pabi_chartfield

[FIX] menu error

---

pabi_pos/models/pos_web_interface.py
pabi_pos/models/stock.py

Branch: #5055-PosCheckStock"
Issue: https://mobileapp.nstda.or.th/redmine/issues/5055

#5055-PosCheckStock

---

pabi_stock_inventory_value/__init__.py
pabi_stock_inventory_value/__openerp__.py
pabi_stock_inventory_value/models/__init__.py
pabi_stock_inventory_value/models/product.py

ทำให้ระบบแสดง standard price เป็น 4 digits
deployment : restart and update module pabi_stock_inventory_value

[ADD] pabi_stock_inventory_value

---

pabi_jobs_hook/__init__.py
pabi_jobs_hook/models/__init__.py
pabi_jobs_hook/models/account.py
pabi_jobs_hook/models/account_budget.py

New module for schedule hook jobs
- Release all commited budget PR
- Release all commited budget EX
- Recompute Adjustment for document JV

#4865 pabi jobs hook

---

pabi_account/models/account_invoice.py
pabi_purchase_work_acceptance/models/account_invoice.py
pabi_purchase_work_acceptance/views/account_invoice_view.xml
pabi_purchase_work_acceptance/views/purchase_work_acceptance_view.xml
pabi_purchase_work_acceptance/views/stock_view.xml
pabi_purchase_work_acceptance/wizard/po_line_invoice.py

- เพิ่ม field Acceptance Date และ Transfer Date ที่ Supplier Invoice
- ที่ WA tree view เปลี่ยนจาก Receive Date เป็น Acceptance Date
- Currency Rate ให้หยิบจาก Acceptance Date และคำนวณอัตราแลกเปลี่ยนตาม Acceptance Date
- หน้า IN ปรับ field ใหม่
- Currency Rate ที่หน้า Invoice ให้ระบบคำนวณจาก Acceptance Date กรณีที่ product เป็น service (หรือ มี product ใดเป็น service) ส่วน Transfer Date ระบบจะคำนวณแบบเดิม
deployment : restart and update module 'pabi_purchase_work_acceptance'

#5040 [FIX] currency rate invoice and wa

---

pabi_purchase_work_acceptance/models/purchase.py

สาเหตุอาจเกิดจากการที่ระบบหา context ที่ส่งมาไม่เจอเลยทำให้ generate ไม่ได้

[FIX] sequence po generate

---

ir_test_action/wizard/ir_test_action.py
pabi_asset_management/models/asset.py

Branch: #5056-ComputeDepreciation
Module: pabi_asset_management,ir_test_action (Restart Only)
Issue: https://mobileapp.nstda.or.th/redmine/issues/5056

#5056-ComputeDepreciation
